import {useState} from 'react';
import {MessageSquare,Send} from 'lucide-react';
import {Dialog} from '../ui/Dialog';
import {gameNames} from '../catalog/catalogs';
import {api} from '../bridge';
import type {Game} from '../types';
export function Feedback({game,version}:{game:Game;version?:string}){
 const [open,setOpen]=useState(false),[type,setType]=useState('Bug report'),[subject,setSubject]=useState(''),[details,setDetails]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 async function send(){if(busy)return;setBusy(true);setError('');try{await api.sendFeedback({game,type,subject,details,email,version:version||__APP_VERSION__});setSent(true);setSubject('');setDetails('');setEmail('');}catch(e){setError(e instanceof Error?e.message:'Unable to send your report. Your draft is kept.');}finally{setBusy(false);}}
 return <section className="panel content-panel"><h2><MessageSquare size={22}/>Reports & suggestions</h2><p>Found a bug or have an idea? Send feedback directly from BancyCraft.</p><button className="button outline" onClick={()=>{setSent(false);setError('');setOpen(true);}}><MessageSquare size={17}/>Report a bug or suggest an idea</button><p className="small muted">Responses are stored in our Google Form. Internet is needed; a Google account is optional.</p>{open&&<Dialog title="Report a bug or suggest an idea" onClose={()=>!busy&&setOpen(false)}>{sent?<><p className="notice" role="status">Your feedback was submitted. Thank you.</p><button className="button outline" onClick={()=>setOpen(false)}>Close</button></>:<form className="feedback-form" onSubmit={e=>{e.preventDefault();void send();}}><label>Type<select aria-label="Report type" disabled={busy} value={type} onChange={e=>setType(e.target.value)}><option>Bug report</option><option>Suggestion</option></select></label><label>Subject<input required maxLength={180} disabled={busy} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What should we look at?"/></label><label>Details<textarea required maxLength={12000} disabled={busy} rows={6} value={details} onChange={e=>setDetails(e.target.value)} placeholder="What happened? What did you expect? How can we reproduce it?"/></label><label>Reply email (optional)<input type="email" maxLength={254} disabled={busy} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><p className="small muted">Includes {gameNames[game]} and BancyCraft {version||__APP_VERSION__}. No workspace, account token or access key is attached. Only include information you want to send.</p>{error&&<p className="notice" role="alert">{error}</p>}<div className="modal-actions"><button className="button primary" disabled={busy||!window.bancy}><Send size={16}/>{busy?'Sending…':'Send report'}</button><button type="button" className="button outline" disabled={busy} onClick={()=>setOpen(false)}>Close</button></div></form>}</Dialog>}</section>;
}
