import {actionLock} from '../../electron/player-lockouts.cjs';
import {useEffect,useState,useRef} from 'react';
import {RefreshCw,Play,Square,Server,Copy,KeyRound,Eye,EyeOff} from 'lucide-react';
import {api} from '../bridge';
import {Dialog} from '../ui/Dialog';
import type {Access,Account,ServerSnapshot} from '../types';
import './servers.css';

const WARMUP_MS=180000;
type Action='start'|'stop'|'restart';
type Command={id:string;label:string;action:Action;switchFrom?:string};
type Warmup=Command&{startedAt:number;accepted:boolean;error?:string};

export function ControllerSettings({access,account,onChange}:{access?:Access;account:Account;onChange:(v:Access)=>void}) {
 const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function act(fn:()=>Promise<Access>){setBusy(true);setError('');try{onChange(await fn());setKey('');}catch(e){setError(e instanceof Error?e.message:'Unable to verify controller access.');}finally{setBusy(false);}}
 return <div className="authentication-key"><h3><KeyRound size={18}/>Server controller key</h3><p>A separately issued key enables server controls for your website account. Community and bank keys do not grant controller access.</p>{access?.unlocked?<><p>{access.subject} · expires {new Date(access.expiresAt!).toLocaleDateString()}</p><button className="button outline" disabled={busy} onClick={()=>act(api.lockController)}>Remove controller key</button></>:<form onSubmit={e=>{e.preventDefault();void act(()=>api.unlockController(key));}}><label>Controller key<input type="password" autoComplete="off" maxLength={3000} value={key} onChange={e=>setKey(e.target.value)} aria-label="Server controller key"/></label><button className="button outline" disabled={busy||!key||account.state!=='connected'}>Verify key</button><p className="muted small">Connect your website account first. Keys are verified online and saved with Windows encryption.</p></form>}{error&&<p role="alert">{error}</p>}</div>;
}

export function Servers({controller,account}:{controller?:Access;account:Account}) {
 const [data,setData]=useState<ServerSnapshot>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<Command>(),[notice,setNotice]=useState(''),[refreshing,setRefreshing]=useState(false),[tab,setTab]=useState<'servers'|'controllers'>('servers'),[revealed,setRevealed]=useState<string[]>([]),[warmup,setWarmup]=useState<Warmup>(),[now,setNow]=useState(Date.now());
 const activeTab=controller?.unlocked?tab:'servers';
 const running=(status:string)=>/^(running|online|active)(?:\b|$)|^up\b/i.test(status.trim());
 const controlServers=data?.control?.servers||[];
 const activeServer=controlServers.find(s=>s.status==='running');
 const registry=[...(data?.registry||[])].sort((a,b)=>Number(running(controlServers.find(c=>c.id===b.controllerServerId)?.status||b.status))-Number(running(controlServers.find(c=>c.id===a.controllerServerId)?.status||a.status)));
 const controls=[...controlServers].sort((a,b)=>Number(running(b.status))-Number(running(a.status)));
 const refreshPending=useRef(false);
 async function refresh(){if(refreshPending.current)return;refreshPending.current=true;setRefreshing(true);setError('');try{setData(await api.serversSnapshot());}catch(e){setError(e instanceof Error?e.message:'Unable to load servers.');}finally{refreshPending.current=false;setRefreshing(false);}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer);},[account.user?.uid,controller?.unlocked]);
 useEffect(()=>{if(!warmup)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[!!warmup]);
 async function copyAddress(address:string){try{await api.copyText(address);setNotice('Address copied.');}catch{setError('Unable to copy address.');}}
 async function action(){if(!confirm||busy)return;const current=confirm;setConfirm(undefined);setBusy(true);setError('');setNow(Date.now());setWarmup({...current,startedAt:Date.now(),accepted:false});try{await api.serverAction(current.id,current.action);setNotice(`${current.switchFrom?'Switch':'Server '+current.action} requested for ${current.label}.`);setWarmup(w=>w&&{...w,accepted:true});await refresh();}catch(e){const message=e instanceof Error?e.message:'Server action failed.';setError(message);setWarmup(w=>w&&{...w,error:message,accepted:true});}finally{setBusy(false);}}
 const elapsed=warmup?Math.max(0,now-warmup.startedAt):0;
 const progress=warmup?.action==='stop'?(warmup.accepted?100:5):Math.min(100,Math.round(elapsed/WARMUP_MS*100));
 const remaining=Math.max(0,Math.ceil((WARMUP_MS-elapsed)/1000));
 const countdown=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
 const verb=(command:Command)=>command.switchFrom?'Switch':command.action==='restart'?'Restart':command.action==='stop'?'Stop':'Start';
 return <>
  <div className="page-heading"><div><p className="eyebrow">BANCY.GG · YOUR WORLDS</p><h1>Servers</h1><p>The website server registry and authorized Blackbox controls.</p></div><button className="button outline" disabled={busy||refreshing||account.state!=='connected'} onClick={()=>refresh()}><RefreshCw size={17} className={refreshing?'spin':''}/>{refreshing?'Refreshing…':'Refresh'}</button></div>
  {account.state!=='connected'&&<p className="notice">Connect your Bancy.gg account in Settings to load server information.</p>}{error&&<p className="notice" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{activeTab==='controllers'&&data?.controlError&&<p className="notice" role="alert">{data.controlError}</p>}
  <div className="actions server-tabs" role="tablist" aria-label="Server views"><button role="tab" aria-selected={activeTab==='servers'} aria-controls="server-registry" className={'button '+(activeTab==='servers'?'primary':'outline')} onClick={()=>setTab('servers')}>Servers</button>{controller?.unlocked&&<button role="tab" aria-selected={activeTab==='controllers'} aria-controls="server-controller" className={'button '+(activeTab==='controllers'?'primary':'outline')} onClick={()=>setTab('controllers')}>Server controllers</button>}</div>
  {activeTab==='servers'&&<div id="server-registry" role="tabpanel" aria-label="Servers" className="server-grid">{registry.map(s=><article className="panel server-card" key={s.id}><h2><Server size={21}/> {s.title}</h2><p>{s.description}</p><dl className="server-facts"><dt>Game</dt><dd>{s.game||s.title}</dd><dt>Status</dt><dd>{controlServers.find(c=>c.id===s.controllerServerId)?.status||s.status}</dd>{s.region&&<><dt>Region</dt><dd>{s.region}</dd></>}{s.host&&<><dt>Host</dt><dd>{s.host}</dd></>}{s.address&&<><dt>Address</dt><dd><span className="server-fact-value"><span>{s.address}</span><button className="icon-button server-copy" title="Copy server address" aria-label={'Copy address '+s.title} onClick={()=>void copyAddress(s.address)}><Copy size={14}/></button></span></dd></>}{s.password&&<><dt>Password</dt><dd><span className="server-fact-value"><span>{revealed.includes(s.id)?s.password:'•••••'}</span><button className="icon-button server-copy" title={revealed.includes(s.id)?'Hide password':'Reveal password'} aria-label={(revealed.includes(s.id)?'Hide':'Reveal')+' password for '+s.title} onClick={()=>setRevealed(v=>v.includes(s.id)?v.filter(id=>id!==s.id):[...v,s.id])}>{revealed.includes(s.id)?<EyeOff size={14}/>:<Eye size={14}/>}</button></span></dd></>}</dl>{s.notes&&<p>{s.notes}</p>}{s.rules.length>0&&<details><summary>Server rules</summary><ul>{s.rules.map((r,n)=><li key={n}>{r}</li>)}</ul></details>}</article>)}</div>}
  {activeTab==='controllers'&&controller?.unlocked&&<section id="server-controller" role="tabpanel" aria-label="Server controllers" className="content-panel"><h2>Blackbox controller</h2><p className="muted">All actions lock while anyone is online or the live player count cannot be verified. Actions require confirmation.</p><div className="server-grid">{controls.map(s=>{const lock=actionLock(data?.control,s.id,'restart');return <article className="panel server-card" key={s.id}><h3>{s.label}</h3><p className="server-status">{s.status}</p><p className="server-players">{s.playersOnline??'?'} / {s.playersMax||'?'} players{s.playerNames?.length?' · '+s.playerNames.join(', '):''}</p>{lock.startsWith('Locked:')&&<p className="notice compact">{lock}</p>}<div className="actions server-actions">{(['start','stop','restart'] as const).map(a=>{const reason=actionLock(data?.control,s.id,a),isSwitch=a==='start'&&!!activeServer&&activeServer.id!==s.id,isRunning=a==='start'&&s.status==='running',command={id:s.id,label:s.label,action:a,...(isSwitch?{switchFrom:activeServer.label}:{})};return <button className="button outline" key={a} disabled={busy||!!warmup||!!reason} title={reason||('Request '+(isSwitch?'switch':a))} onClick={()=>setConfirm(command)}>{a==='start'?<Play size={15}/>:a==='stop'?<Square size={15}/>:<RefreshCw size={15}/>} {isSwitch?'Switch':isRunning?'Running':a[0].toUpperCase()+a.slice(1)}</button>;})}</div></article>;})}</div></section>}
  {confirm&&<Dialog title={'Confirm '+verb(confirm).toLowerCase()} onClose={()=>!busy&&setConfirm(undefined)}><p>{confirm.switchFrom?`Switch from ${confirm.switchFrom} to ${confirm.label}?`:`${verb(confirm)} ${confirm.label}?`}</p><p>This can disconnect players. The controller will check player counts again before sending the command.</p><div className="modal-actions"><button className="button outline" disabled={busy} onClick={()=>setConfirm(undefined)}>Cancel</button><button className="button danger" disabled={busy} onClick={()=>void action()}>Confirm {verb(confirm).toLowerCase()}</button></div></Dialog>}
  {warmup&&<Dialog title={warmup.error?'Controller command failed':`${warmup.switchFrom?'Switching to':warmup.action==='restart'?'Restarting':warmup.action==='stop'?'Stopping':'Starting'} ${warmup.label}`} onClose={()=>!busy&&setWarmup(undefined)}><div className="server-warmup"><p>{warmup.error||(!warmup.accepted?'Sending the command to Blackbox.':warmup.action==='stop'?'Blackbox accepted the stop command.':'Blackbox accepted the command. Waiting for the world to warm up.')}</p>{warmup.action!=='stop'&&<strong>{countdown} estimated warmup remaining</strong>}<div className="server-warmup-track" role="progressbar" aria-label="Estimated server warmup progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><span style={{width:`${progress}%`}}/></div><small>{warmup.error?'The action did not complete.':warmup.action==='stop'?warmup.accepted?'Command accepted. Refresh server status to verify shutdown.':'Waiting for acknowledgement.':`${progress}% of the website's three-minute warmup estimate. Server status refreshes automatically.`}</small><button className="button outline" disabled={busy} onClick={()=>setWarmup(undefined)}>Close</button></div></Dialog>}
 </>;
}
