import {useState} from 'react';
import {BarChart3,BookOpen} from 'lucide-react';
import {useTools} from '../tools/useTools';
import type {Workspace} from '../types';
import {gameNames} from '../catalog/catalogs';
const guide=[
 ['Choose your game','Use the game selector at the top or a home tile. Searches, supplies, gearsets, builds and lists belong to that game. Changing games does not delete your work. Dune: Awakening is planned.'],
 ['Find items and recipes','The Item Browser searches only your selected game. Use Type and Item type filters, pagination, quantities and multi-selection. + adds items to a saved list; the clock creates a quick list that removes itself when finished. Item source buttons open the source site. Favorites and recent items help you return to regular crafts.'],
 ['Work through a shopping list','Open a compact card to enter its workspace. Add items searches in a modal and adds directly to this list. Expand Vendors, Gathering, Other sources, Pre-crafts and Target items, or switch to Crafting stations. Recipe menus choose an alternative or direct acquisition. The branch icon opens a crafting tree with quantities and stations; the pencil changes a target quantity. Completing a craft satisfies its used inputs. Shared ingredients still needed elsewhere stay outstanding. Reset restores incomplete progress; Undo respects newer shared edits.'],
 ['Track supplies','My Supplies links each entry to this game’s catalog. Select a matching item, then enter the quantity you own. Count My Supplies allocates stock within a private list and deducts used stock once when the list finishes. Stock is not reserved between unfinished lists. Resetting and recompleting a finished list does not deduct twice. Shared lists use their own Already have entries and do not consume personal stock.'],
 ['Gearsets and builds','Gearsets are prepared bundles. Builds let you select equipment, food and potions, name the build, add tags, description and play notes. Opening a saved build is view-only; owners click Edit. Unsupported slots use a crossed-out symbol and two-handed weapons lock the off-hand. Create full shopping list turns selected items into craft targets. Create variant saves an independent private copy.'],
 ['Share with friends','Connect your website account in Settings. Shared lists appear below private lists; invite a website member to work together. Progress and assignments update live while connected. Shared builds are visible to signed-in members. Sharing moves your build out of My builds; Unshare returns it. Only its owner can edit, unshare or delete it. Save Build to My Builds creates your own private copy; its original author remains credited. Source updates can be reviewed and saved as a new copy.'],
 ['Dragonwilds production ledger','Select Dragonwilds to see Production Ledger. Plan processing, merchant purchase batches, timings and profits locally. The shared bank uses the website’s existing permissions and requires a separately issued community key. Local recipes and ledger calculations work offline.'],
 ['Updates and backups','Installed apps check at startup, every six hours and when Settings & updates opens. Download then restart to install when ready. Your workspace stays outside the installation folder. Back up and Restore include lists, supplies, plans and builds, while account credentials and access keys stay private. Restore asks before replacing local work and saves a previous-state backup.'],
 ['Help and feedback','Settings opens the app feedback form for bugs and suggestions. Include the game, app version, item name and reproducible steps. Metrics below describe this computer’s saved work; they are not uploaded analytics. Completed-list tracking begins in this release.'],
];
export function Help({workspace}:{workspace:Workspace}) {
 const [metrics,setMetrics]=useState(false),tools=useTools();
 const stats=[['Lists completed',(workspace.completionLog||[]).length],['Private lists',workspace.lists.length],['Private builds',tools.data.builds.filter(b=>!b.publishedAt).length],['Shared builds cached',tools.data.builds.filter(b=>b.publishedAt).length],['Supply entries',workspace.supplies.length],['Saved project notes',workspace.plans.length]];
 return <><div className="page-heading"><div><p className="eyebrow">A GOOD PLACE TO START</p><h1>Help</h1><p>Learn your workspace, from your first item to a shared build.</p></div><button className="button outline" onClick={()=>setMetrics(!metrics)}>{metrics?<BookOpen size={18}/>:<BarChart3 size={18}/>} {metrics?'Usage guide':'My metrics'}</button></div>{metrics?<><div className="metric-grid">{stats.map(([label,value])=><article className="panel" key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="panel content-panel"><h2>Completed lists by game</h2>{Object.entries(gameNames).map(([game,name])=><p key={game}>{name}: {(workspace.completionLog||[]).filter(x=>x.game===game).length}</p>)}<p className="muted">Local totals from this release onward. Each private list counts once, including quick lists. Previously deleted lists and shared completions are not included. Metrics stay in your backups.</p></section></>:<section className="panel content-panel guide-content"><h2>Complete usage guide</h2>{guide.map(([title,text],i)=><details name="bancycraft-help" key={title} open={i===0}><summary>{i+1}. {title}</summary><p>{text}</p></details>)}<h2>Frequently asked questions</h2><details name="bancycraft-help"><summary>Do I need an account or Internet?</summary><p>No account is needed for local catalogs, private lists, builds, supplies and the ledger. Sharing, updates, source links and the feedback form need Internet. Bank and controller access require their own keys and website authorization.</p></details><details name="bancycraft-help"><summary>Why is a source or recipe still missing?</summary><p>Some items are loot-only. Catalogs distinguish known acquisition details from incomplete source imports. We show exact crafting input amounts when verified, but never estimate how many creatures or harvests you need. Use the item source link to verify the latest game version.</p></details><details name="bancycraft-help"><summary>Will deleting or sharing change someone’s private copy?</summary><p>Deleting a list removes that list and progress. Deleting a shared build removes its shared entry for everyone; saved independent private copies remain. Unshare returns the owner’s build to My builds.</p></details><details name="bancycraft-help"><summary>Why are image details sometimes soft?</summary><p>Some sources supply only small inventory icons. BancyCraft uses the largest available local artwork, with an icon fallback. No item image is fabricated.</p></details></section>}</>;
}
