import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Box, ChevronLeft, ChevronRight, Clock, ExternalLink, Hammer, Leaf, Plus, Search, Star, X } from 'lucide-react';
import type { Game, ListTarget } from '../types';
import type { Item, Recipe } from './types';
import { api } from '../bridge';
import { catalogs, gameNames } from './catalogs';
import { ItemIcon } from './ItemIcon';
import { broadType, itemSubtype, indexCatalog, itemKey, normalize, canonicalItems } from '../planner/engine.mjs';
import { Dialog } from '../ui/Dialog';
import type { AddRequest } from '../planner/ListPicker';
import './catalog.css';
import {useTools} from '../tools/useTools';
export function ItemBrowser({ game, query, onQuery, onAdd, onQuick, busy }: { game: Game; query: string; onQuery: (value: string) => void; onAdd: (request: AddRequest) => void; onQuick: (request: AddRequest) => void; busy: boolean }) {
  const tools=useTools(),[savedFilter,setSavedFilter]=useState('all');
  const catalog = catalogs[game], index = useMemo(() => indexCatalog(catalog), [catalog]);
  const [type, setType] = useState(''), [category, setCategory] = useState(''), [station, setStation] = useState(''), [sort, setSort] = useState('name');
  const [page, setPage] = useState(0), [additional, setAdditional] = useState(false), [selected, setSelected] = useState<Item>(), [linkError, setLinkError] = useState('');
  const [selection, setSelection] = useState<string[]>([]), [quantities, setQuantities] = useState<Record<string, number>>({});
  useEffect(() => { setPage(0); window.scrollTo({ top: 0 }); }, [query, type, category, station, sort,savedFilter]);
  const categories = useMemo(() => [...new Set(canonicalItems(catalog).map(i => itemSubtype(i)))].sort(), [catalog]);
  const stations = useMemo(() => [...new Set(catalog.recipes.map(r => r.station).filter(Boolean))].sort(), [catalog]);
  const stationOutputs = useMemo(() => new Set(catalog.recipes.filter(r => r.station === station).flatMap(r => r.outputs.map(i => normalize(i.name)))), [catalog, station]);
  const results = useMemo(() => canonicalItems(catalog).filter(item => {
    const crafted = index.recipes.has(itemKey(item));
    return (savedFilter==='all'||(savedFilter==='favorites'?tools.data.favorites[game]:tools.data.recent[game])?.includes(item.id)) && (!type || (type === 'Recipes' ? crafted : broadType(item, crafted) === type)) && (!category || category === itemSubtype(item)) && (!station || stationOutputs.has(normalize(item.name))) && normalize(`${item.name} ${item.id}`).includes(normalize(query));
  }).sort((a, b) => sort === 'type' ? itemSubtype(a).localeCompare(itemSubtype(b)) || a.name.localeCompare(b.name) : sort === 'reverse' ? b.name.localeCompare(a.name) : a.name.localeCompare(b.name)), [catalog, category, type, station, stationOutputs, query, index, sort,savedFilter,tools.data,game]);
  const currentPage = Math.min(page, Math.max(0, Math.ceil(results.length / 50) - 1)), pages = Math.max(1, Math.ceil(results.length / 50));
  const visible = results.slice(currentPage * 50, currentPage * 50 + 50);
  const pageNumbers = [...new Set([0, currentPage - 1, currentPage, currentPage + 1, pages - 1].filter(n => n >= 0 && n < pages))].sort((a, b) => a - b);
  function target(item: Item): ListTarget { return { itemId: item.id, name: item.name, quantity: quantities[item.id] || 1 }; }
  const selectionTargets = selection.map(id => index.byId.get(id)).filter((item): item is Item => Boolean(item)).map(target);
  function toggle(id: string) { setSelection(previous => previous.includes(id) ? previous.filter(value => value !== id) : previous.length < 500 ? [...previous, id] : previous); }
  async function source(url: string) { try { await api.openSource(url); setLinkError(''); } catch { setLinkError('The source link could not be opened.'); } }
  function follow(name: string) { const matches = index.byName.get(normalize(name)) ?? []; if (matches.length === 1) setSelected(matches[0]); else { onQuery(name); setSelected(undefined); setType(''); setCategory(''); setStation(''); } }
  function ingredient(name: string, amount: number, key: string) { return <li key={key}><strong>{amount.toLocaleString()} ×</strong>{index.byName.has(normalize(name)) ? <button onClick={() => follow(name)}>{name}</button> : <span>{name}</span>}</li>; }
  function recipeCard(recipe: Recipe, n: number) { return <article className="recipe-card" key={recipe.id}><div className="recipe-title"><Hammer size={16}/><strong>{recipe.station || 'Station not provided by this source'}</strong><span>Recipe {n + 1}</span></div><div className="recipe-flow"><div><small>INPUTS · PER CRAFT</small><ul>{recipe.inputs.map((i, n) => ingredient(i.name, i.quantity, `input-${n}`))}</ul></div><ChevronRight size={18}/><div><small>OUTPUTS</small><ul>{recipe.outputs.map((i, n) => ingredient(i.name, i.quantity, `output-${n}`))}</ul></div></div>{recipe.notes && <p className="muted small">{recipe.notes}</p>}<button className="text-button" onClick={() => source(recipe.sourceUrl)}>Recipe source <ExternalLink size={12}/></button></article>; }
  const madeBy = selected ? index.recipes.get(itemKey(selected)) ?? [] : [];
  const usedBy = selected && index.byName.get(normalize(selected.name))?.length === 1 ? catalog.recipes.filter(r => r.inputs.some(i => i.itemId ? i.itemId === selected.id : normalize(i.name) === normalize(selected.name))) : [];
  function pagination() { return <div className="numbered-pagination"><span>{results.length ? `${currentPage * 50 + 1}–${Math.min((currentPage + 1) * 50, results.length)}` : '0'} of {results.length.toLocaleString()} items</span><button className="icon-button" aria-label="Previous results" disabled={!currentPage} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={16}/></button>{pageNumbers.map((n, i) => <span key={n} className="page-number-wrap">{i > 0 && n - pageNumbers[i - 1] > 1 && <span>…</span>}<button className={`page-number ${n === currentPage ? 'active' : ''}`} aria-label={`Results page ${n + 1}`} aria-current={n === currentPage ? 'page' : undefined} onClick={() => setPage(n)}>{n + 1}</button></span>)}<button className="icon-button" aria-label="Next results" disabled={currentPage + 1 >= pages} onClick={() => setPage(currentPage + 1)}><ChevronRight size={16}/></button></div>; }
  return <section className="catalog" aria-label={`${gameNames[game]} item browser`}>
    <div className="page-heading"><div><p className="eyebrow">SEARCH · SELECT · MAKE A LIST</p><h1>Item browser</h1><p>{gameNames[game]} <span className="catalog-dot">/</span> {canonicalItems(catalog).length.toLocaleString()} imported items · Available offline</p></div><BookOpen size={34} strokeWidth={1}/></div>
    <div className="panel search-panel"><div className="catalog-filters"><label>Type<select aria-label="Search type" value={type} onChange={e => setType(e.target.value)}><option value="">All items</option>{['Recipes', 'Materials', 'Weapons', 'Armor', 'Consumables', 'Quest items', 'Crafted items', 'Other items'].map(t => <option key={t}>{t}</option>)}</select></label><label>Item type<select aria-label="Item type" value={category} onChange={e => setCategory(e.target.value)}><option value="">All item types</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Sort by<select aria-label="Sort results" value={sort} onChange={e => setSort(e.target.value)}><option value="name">Name A–Z</option><option value="reverse">Name Z–A</option><option value="type">Item type</option></select></label></div><label className="catalog-search"><Search size={20}/><input aria-label="Search catalog" placeholder={`Search ${gameNames[game]} items…`} value={query} onChange={e => onQuery(e.target.value)}/></label><div className="filter-options"><button className="text-button" onClick={() => setAdditional(!additional)}>{additional ? 'Hide' : 'Show'} additional filters</button><button className="text-button" onClick={() => { onQuery(''); setType(''); setCategory(''); setStation(''); setSort('name'); }}>Reset filters</button></div>{additional && <label className="station-filter">Crafting station<select aria-label="Crafting station" value={station} onChange={e => setStation(e.target.value)}><option value="">All stations</option>{stations.map(s => <option key={s}>{s}</option>)}</select></label>}</div>
    <div className="actions saved-item-filters">{['all','favorites','recent'].map(f=><button key={f} className={'button '+(savedFilter===f?'primary':'outline')} onClick={()=>setSavedFilter(f)}>{f==='all'?'All items':f==='favorites'?'Favorites':'Recently viewed'}</button>)}</div>{tools.error&&<p role="alert">{tools.error}</p>}
    <div className="select-all"><button className="button outline" onClick={() => setSelection(results.slice(0, 500).map(i => i.id))} disabled={!results.length}>Select all results{results.length > 500 ? ' (first 500)' : ''}</button>{selection.length > 0 && <span>{selection.length} selected across pages <button className="text-button" onClick={() => setSelection([])}>Clear selection</button></span>}</div>
    {selection.length >= 2 && <section className="panel selection-panel" aria-label="Selected items"><header>Selection · {selection.length} items</header><div className="selection-chips">{selectionTargets.map(t => <div key={t.itemId}><ItemIcon game={game} id={t.itemId}/><span>{t.name}<small>×{t.quantity}</small></span><button aria-label={`Unselect ${t.name}`} onClick={() => toggle(t.itemId)}><X size={15}/></button></div>)}</div><div className="actions"><button className="button primary" disabled={busy} onClick={() => onAdd({ game, targets: selectionTargets })}><Plus size={16}/>Add selection to a list</button><button className="button outline" disabled={busy} onClick={() => onQuick({ game, targets: selectionTargets })}><Clock size={16}/>Create quick list</button><button className="text-button" onClick={() => setSelection([])}>Reset selection</button></div></section>}
    {pagination()}{linkError && <p role="alert">{linkError}</p>}
    <div className="panel search-results">{visible.length ? visible.map(item => <div key={item.id} className="search-result"><input type="checkbox" aria-label={`Select ${item.name}`} checked={selection.includes(item.id)} onChange={() => toggle(item.id)}/><ItemIcon game={game} id={item.id}/><button className="result-name" aria-label={`View ${item.name}`} onClick={() => {setSelected(item);void tools.save(v=>({...v,recent:{...v.recent,[game]:[item.id,...(v.recent[game]||[]).filter(id=>id!==item.id)].slice(0,100)}}));}}>{item.name}<small>{itemSubtype(item)}{game === 'valheim' && ` · ${item.id}`}{' · '+(index.recipes.has(itemKey(item))?'Craftable':item.acquisition?'Gather / loot / vendor source':'Recipe/source missing')}</small></button><button className="icon-button favorite-action" aria-label={'Favorite '+item.name} aria-pressed={tools.data.favorites[game]?.includes(item.id)||false} disabled={tools.busy} onClick={()=>tools.save(v=>({...v,favorites:{...v.favorites,[game]:(v.favorites[game]||[]).includes(item.id)?(v.favorites[game]||[]).filter(id=>id!==item.id):[...(v.favorites[game]||[]),item.id]}}))}><Star size={16}/></button><label className="result-quantity"><span className="sr-only">Quantity for {item.name}</span><input type="number" min="1" max="999999" step="1" value={quantities[item.id] || 1} onChange={e => { const number = Number(e.target.value); setQuantities(q => ({ ...q, [item.id]: Number.isSafeInteger(number) && number >= 1 && number <= 999999 ? number : 1 })); }}/></label><button className="round-action" aria-label={`Add ${item.name} to list`} title="Add to list" disabled={busy} onClick={() => onAdd({ game, targets: [target(item)] })}><Plus size={18}/></button><button className="round-action" aria-label={`Quick list for ${item.name}`} title="Create quick list" disabled={busy} onClick={() => onQuick({ game, targets: [target(item)] })}><Clock size={18}/></button></div>) : <div className="empty-state"><Search size={32}/><h2>No matching items</h2><p>Try another name or reset the filters. Searches only include {gameNames[game]}.</p></div>}</div>
    {pagination()}
    <details className="catalog-provenance"><summary>Game version, sources & coverage · Imported {new Date(catalog.importedAt).toLocaleDateString()}</summary><p>{catalog.coverage}</p><p>Adapted from {catalog.source.name}. {catalog.source.license}. {catalog.source.version}</p><div className="actions"><button className="text-button" onClick={() => source(catalog.source.url)}>Source <ExternalLink size={12}/></button><button className="text-button" onClick={() => source(catalog.source.licenseUrl)}>License <ExternalLink size={12}/></button></div></details>
    {selected && <Dialog title={selected.name} onClose={() => setSelected(undefined)}><div className="item-detail" aria-label="Item details"><div className="detail-identity"><ItemIcon key={selected.id} game={game} id={selected.id}/><div><p className="eyebrow">{gameNames[game]} / {selected.category}</p><h2>{selected.name}</h2></div></div>{selected.description && <p>{selected.description}</p>}<div className="actions"><button className="button primary" disabled={busy} onClick={() => { onAdd({ game, targets: [target(selected)] }); setSelected(undefined); }}><Plus size={16}/>Add to list</button><button className="text-button" onClick={() => source(selected.sourceUrl)}>Open item source <ExternalLink size={13}/></button></div><section><h3><Hammer size={18}/>How to craft</h3>{madeBy.length ? madeBy.map((r, n) => recipeCard(r.recipe, n)) : <p className="catalog-empty-note">No crafting recipe imported for this item. It may be gathered, dropped, purchased, or not yet covered.</p>}</section><section><h3><Leaf size={18}/>Where to find it</h3><p className="catalog-empty-note">{selected.acquisition || 'Acquisition details are not yet imported. Check the source page.'}</p><p className="small muted">Gathering and drops are descriptive. Material needs are never converted into creature or harvest counts.</p></section><section><h3><Box size={18}/>Used in ({usedBy.length})</h3>{usedBy.length ? usedBy.map(recipeCard) : <p className="catalog-empty-note">No uses recorded in the imported recipes.</p>}</section></div></Dialog>}
  </section>;
}
