const { test } = require('node:test'), assert = require('node:assert/strict'), fs = require('fs');
test('crafting tree keeps every input beneath its parent, including shared branches', async () => { const { buildCraftingTree } = await import('../src/planner/tree.mjs'); const item = n => ({ id: n, name: n, category: 'Materials', description: '', acquisition: '' }); const catalog = { items: ['Root', 'Left', 'Right', 'Thread', 'Plant'].map(item), recipes: [{ id: 'root', station: 'Forge', inputs: [{ name: 'Left', quantity: 1, itemId: 'Left' }, { name: 'Right', quantity: 1, itemId: 'Right' }], outputs: [{ name: 'Root', quantity: 1, itemId: 'Root' }] }, { id: 'left', station: 'Bench', inputs: [{ name: 'Thread', quantity: 1, itemId: 'Thread' }], outputs: [{ name: 'Left', quantity: 1, itemId: 'Left' }] }, { id: 'right', station: 'Bench', inputs: [{ name: 'Thread', quantity: 1, itemId: 'Thread' }], outputs: [{ name: 'Right', quantity: 1, itemId: 'Right' }] }, { id: 'thread', station: 'Loom', inputs: [{ name: 'Plant', quantity: 3, itemId: 'Plant' }], outputs: [{ name: 'Thread', quantity: 4, itemId: 'Thread' }] }] }; const list = { targets: [], recipes: {}, progress: { 'i:Root': 99 }, useSupplies: true }; const tree = buildCraftingTree(list, catalog, { item: item('Root'), name: 'Root' }, 1); assert.equal(tree.edges.filter(e => e.from.row.name === 'Root').length, 2); assert.equal(tree.nodes.filter(n => n.row.name === 'Thread').length, 2); assert.equal(tree.edges.filter(e => e.to.row.name === 'Thread').length, 2); assert(tree.nodes.filter(n => n.row.name === 'Thread').every(n=>n.row.required===1&&n.row.recipe.station==='Loom')); const direct = buildCraftingTree({ ...list, recipes: { 'i:Thread': 'gather' } }, catalog, { item: item('Root'), name: 'Root' }, 1); assert(!direct.nodes.some(n => n.row.name === 'Plant')); assert.throws(() => buildCraftingTree(list, catalog, { item: item('Root'), name: 'Root' }, 0)); assert.equal(list.progress['i:Root'], 99); });
test('crafting tree shows real Dragonwilds loom inputs and exact batch quantities', async () => { const { buildCraftingTree } = await import('../src/planner/tree.mjs'), catalog = require('../src/catalog/data/dragonwilds.json'), item = catalog.items.find(i => i.name === 'Vis Cloth'); assert(item); const recipe = catalog.recipes.find(r => r.outputs.some(o => o.name === item.name) && /loom/i.test(r.station)); assert(recipe); const tree = buildCraftingTree({ targets: [], progress: {}, recipes: { ['i:' + item.id]: recipe.id } }, catalog, { item, name: item.name }, 5), root = tree.nodes.find(n => n.row.isTarget).row; assert.match(root.recipe.station, /loom/i); for (const input of recipe.inputs) {
    const node = tree.nodes.find(n => n.row.name === input.name);
    assert(node);
    assert(node.row.required >= input.quantity * Math.ceil(5 / root.output));
} });
test('Rune Platebody diagram shows all five wiki recipe inputs directly under the armor', async()=>{const {buildCraftingTree}=await import('../src/planner/tree.mjs'),catalog=require('../src/catalog/data/dragonwilds.json'),item=catalog.items.find(i=>i.name==='Rune Platebody'),tree=buildCraftingTree({targets:[],progress:{},recipes:{},owned:{},useSupplies:false},catalog,{item,name:item.name},1),children=tree.edges.filter(e=>e.from.row.key==='root').map(e=>e.to.row.name);assert.deepEqual(children,['Rune Bar','Black Dragon Leather','Vis Cloth','Harmonised Compound','Draconic Vis Wax']);});
test('every Dragonwilds recipe output resolves to a catalog item, including gilded capes',async()=>{const {indexCatalog}=await import('../src/planner/engine.mjs'),catalog=require('../src/catalog/data/dragonwilds.json'),index=indexCatalog(catalog);for(const recipe of catalog.recipes)for(const output of recipe.outputs)assert(index.resolve(output),`${recipe.id}: ${output.name}`);assert(index.byName.get('golden bloodblight cape')?.length===1);});
test('bundled changelog includes every historical release and all release notes', async () => { const { parseChangelog } = await import('../src/updates/release-history.mjs'); const raw = fs.readFileSync(require('path').join(__dirname, '../CHANGELOG.md'), 'utf8'), releases = parseChangelog(raw); assert.equal(releases.length, (raw.match(/^## /gm) || []).length); assert.equal(releases[0].version, require('../package.json').version); assert.equal(releases.at(-1).version, '0.1.0'); for (const r of releases)
    assert(r.blocks.length); assert(releases.find(r => r.version === '0.4.1').blocks.flatMap(b => b.lines).some(t => t.includes('top-right'))); });
test('V Rising preserves station rowspans, equipment upgrades and rejects unknown material counts', () => { const { recipes } = require('../scripts/catalog/vrising-parse.cjs'); const raw = `{|\n!Item!!Materials!!Structure\n|-\n|{{ItemFrame|A|type=Armour}}\n|rowspan="2"|{{ItemFrame|Prior A|type=Armour}}<br>{{ItemFrame|Cloth|4}}\n|rowspan="2"|{{ItemFrame|Tailoring Bench|type=Structure}}\n|-\n|{{ItemFrame|B|type=Armour}}\n|}`; const parsed = recipes(raw, 'Armor'); assert.equal(parsed.length, 2); assert.equal(parsed[1].station, 'Tailoring Bench'); assert.equal(parsed[0].inputs[0].quantity, 1); assert.equal(parsed[1].inputs[1].quantity, 4); assert.equal(recipes(raw.replace('Cloth|4', 'Cloth|2–5'), 'Armor').length, 0); assert.equal(recipes(raw.replace('Cloth|4', 'Cloth'), 'Armor').length, 0); });
test('V Rising catalog uses current primary crafting sources and referenced local icons', () => { const catalog = require('../src/catalog/data/vrising.json'), icons = require('../src/catalog/data/icons.json').vrising, sets = require('../src/catalog/data/gearsets.json').vrising; assert(catalog.items.length > 500 && catalog.recipes.length > 300 && sets.length >= 25); const cloth = catalog.recipes.filter(r => r.outputs.some(i => i.name === 'Cloth')); assert.equal(cloth.length, 3); assert(cloth.every(r => r.sourceUrl.endsWith('/Cloth'))); assert(!sets.some(s => s.name === 'Bloodmoon Armour Set')); assert(sets.find(s => s.name === 'Dread Plate Armour Set').ids.length === 4); for (const r of catalog.recipes)
    for (const i of [...r.inputs, ...r.outputs])
        assert(catalog.items.some(item => item.id === i.itemId)); assert(Object.keys(icons).length > 500); for (const url of Object.values(icons))
    assert(fs.existsSync(require('path').join(__dirname, '../public', url.replace('./', '')))); });
