const {cleanBuild}=require('./tools-store.cjs');
function createBuilds(account,options={}){
 const network=options.fetch||((...args)=>fetch(...args));
 const user=()=>{const u=account.status();if(u.state!=='connected'||!u.user)throw Error('Connect your Bancy.gg account to browse or share builds.');return {uid:u.user.uid,displayName:u.user.displayName};};
 const id=v=>{if(typeof v!=='string'||! /^[a-f0-9-]{36}$/.test(v))throw Error('Invalid build ID.');return v;};
 async function request(route,init={}){user();const url=new URL(account.config.databaseURL+'/'+route+'.json');url.searchParams.set('auth',await account.token());const r=await network(url,{...init,headers:{'Content-Type':'application/json',...init.headers},signal:AbortSignal.timeout(20000)});if(r.status===412)throw Error('This build was updated elsewhere. Refresh before publishing again.');if(!r.ok)throw Error('Unable to access shared builds. Check your connection and website account.');return r;}
 const get=async key=>{const r=await request('bancycraftBuilds/'+id(key));const value=await r.json();return value?{...cleanBuild(value),publishedAt:value.updatedAt}:null;};
 return {
  get,
  async browse(game){if(!['dragonwilds','valheim','enshrouded','grounded2','vrising'].includes(game))throw Error('Invalid game.');const route='bancycraftBuilds';user();const url=new URL(account.config.databaseURL+'/'+route+'.json');url.searchParams.set('auth',await account.token());url.searchParams.set('orderBy',JSON.stringify('game'));url.searchParams.set('equalTo',JSON.stringify(game));url.searchParams.set('limitToFirst','200');const r=await network(url,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Unable to browse shared builds.');return Object.values(await r.json()||{}).map(v=>({...cleanBuild(v),publishedAt:v.updatedAt}));},
  async publish(value){const build=cleanBuild(value),owner=user();id(build.id);const r=await request('bancycraftBuilds/'+build.id,{headers:{'X-Firebase-ETag':'true'}}),old=await r.json();if(old&&old.owner.uid!==owner.uid)throw Error('Only the owner can update a shared build.');if(old&&old.updatedAt!==(build.publishedAt||build.updatedAt))throw Error('This build was updated elsewhere. Refresh before publishing again.');let creator=old?.creator||owner;if(!old&&build.sourceId){const source=await get(build.sourceId);if(source)creator=source.creator||source.owner;}
   const next={...build,owner,creator,updatedAt:new Date().toISOString()};delete next.publishedAt;await request('bancycraftBuilds/'+build.id,{method:'PUT',headers:{'If-Match':r.headers.get('etag')||'null_etag'},body:JSON.stringify(next)});return {...next,publishedAt:next.updatedAt};},
  async remove(key){await request('bancycraftBuilds/'+id(key),{method:'DELETE'});},
  async avatar(uid){if(typeof uid!=='string'||! /^[A-Za-z0-9_-]{1,128}$/.test(uid))throw Error('Invalid profile.');const profile=await (await request('publicProfiles/'+uid)).json();const inline=String(profile?.photoURL||'');if(/^data:image\/(?:png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(inline)&&inline.length<=1250000){const bytes=Buffer.from(inline.split(',')[1],'base64');if(bytes.length>950000)return null;return {uid,displayName:String(profile.displayName||'Member').slice(0,32),image:inline};}let url;try{url=new URL(profile?.photoURL);}catch{return null;}if(url.protocol!=='https:'||!['lh3.googleusercontent.com','lh4.googleusercontent.com','lh5.googleusercontent.com','lh6.googleusercontent.com','firebasestorage.googleapis.com','bancy.gg','www.bancy.gg','i.imgur.com','cdn.discordapp.com'].includes(url.hostname))return null;const r=await network(url,{signal:AbortSignal.timeout(10000),redirect:'error'});const type=r.headers.get('content-type')?.split(';')[0];if(!r.ok||!['image/png','image/jpeg','image/webp','image/gif'].includes(type)||Number(r.headers.get('content-length'))>1000000)return null;const reader=r.body.getReader();let size=0,parts=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>1000000){await reader.cancel();return null;}parts.push(Buffer.from(value));}return {uid,displayName:String(profile.displayName||'Member').slice(0,32),image:'data:'+type+';base64,'+Buffer.concat(parts).toString('base64')};}
 };
}
module.exports={createBuilds};
