const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bancy', Object.freeze({
  adminKeys:()=>ipcRenderer.invoke('admin:keys'),copyAdminKey:id=>ipcRenderer.invoke('admin:copy-key',id),sendFeedback:v=>ipcRenderer.invoke('feedback:send',v),
  accountConnect: () => ipcRenderer.invoke('account:connect'), accountDisconnect: () => ipcRenderer.invoke('account:disconnect'),
  sharedStatus: () => ipcRenderer.invoke('shared:status'), sharedWatch: id => ipcRenderer.invoke('shared:watch',id),
  sharedCreate: id => ipcRenderer.invoke('shared:create',id), sharedChange: (id,base,next) => ipcRenderer.invoke('shared:change',id,base,next),
  sharedSearch: text => ipcRenderer.invoke('shared:search',text), sharedAdd: (id,uid) => ipcRenderer.invoke('shared:add',id,uid),
  sharedRemoveMember: (id,uid) => ipcRenderer.invoke('shared:removeMember',id,uid), sharedRemove: id => ipcRenderer.invoke('shared:remove',id),
  sharedRestore:id=>ipcRenderer.invoke('shared:restore',id),
  onShared: callback => { const listener = (_event,data) => callback(data); ipcRenderer.on('shared:status',listener);return () => ipcRenderer.removeListener('shared:status',listener); },
  toolsLoad:()=>ipcRenderer.invoke('tools:read'),toolsSave:v=>ipcRenderer.invoke('tools:write',v),
  buildsBrowse:g=>ipcRenderer.invoke('builds:browse',g),buildsGet:id=>ipcRenderer.invoke('builds:get',id),buildsPublish:b=>ipcRenderer.invoke('builds:publish',b),buildsRemove:id=>ipcRenderer.invoke('builds:remove',id),profileAvatar:uid=>ipcRenderer.invoke('profile:avatar',uid),
  importWorkspace:()=>ipcRenderer.invoke('workspace:import'),exportList:l=>ipcRenderer.invoke('list:export',l),importList:()=>ipcRenderer.invoke('list:import'),exportBuild:b=>ipcRenderer.invoke('build:export',b),importBuild:()=>ipcRenderer.invoke('build:import'),gamingMode:e=>ipcRenderer.invoke('gaming:mode',e),
  unlockController:key=>ipcRenderer.invoke('controller:unlock',key),lockController:()=>ipcRenderer.invoke('controller:lock'),serversSnapshot:()=>ipcRenderer.invoke('servers:snapshot'),serverAction:(id,action)=>ipcRenderer.invoke('servers:action',id,action),
  copyText:value=>ipcRenderer.invoke('clipboard:copy',value),
  info: () => ipcRenderer.invoke('app:info'),
  unlockCommunity: key => ipcRenderer.invoke('community:unlock', key),
  lockCommunity: () => ipcRenderer.invoke('community:lock'),
  openBank: order => ipcRenderer.invoke('community:bank',order),
  load: () => ipcRenderer.invoke('workspace:read'),
  save: data => ipcRenderer.invoke('workspace:write', data),
  openSource: url => ipcRenderer.invoke('source:open', url),
  openWebsite: () => ipcRenderer.invoke('website:open'),
  openDonation: () => ipcRenderer.invoke('donation:open'),
  openData: () => ipcRenderer.invoke('data:open'),
  exportWorkspace: () => ipcRenderer.invoke('workspace:export'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdate: callback => { const listener = (_event, data) => callback(data); ipcRenderer.on('update:status', listener); return () => ipcRenderer.removeListener('update:status', listener); }
}));
