// Source-backed refresh and deterministic audit. No yield estimates for gathering/loot.
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),sharp=require('sharp');
const {document}=require('./supplement.cjs');
const root=path.resolve(__dirname,'../..'),cache=path.join(root,'.catalog-cache');
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
async function request(url){const file=path.join(cache,hash(url)+'.json');try{return JSON.parse(await fs.readFile(file,'utf8'));}catch{}const r=await fetch(url,{headers:{'User-Agent':'BancyCraft catalog coverage audit; https://github.com/d-bergman/bancycraft'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Source HTTP '+r.status);const value={url,fetchedAt:new Date().toISOString(),text:await r.text()};await fs.writeFile(file,JSON.stringify(value));return value;}
async function run(){const {canonicalItems,indexCatalog,buildShoppingList}=await import('../../src/planner/engine.mjs');
 const upgrades=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/valheim-upgrades.json'),'utf8'));const catalog=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/valheim.json'),'utf8')),items=canonicalItems(catalog),names=new Map(items.map(i=>[i.name.toLowerCase(),i]));
 const retired=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/valheim-inactive-recipes.json'),'utf8').catch(()=>'[]'));const report={mode:process.argv.includes('--report-only')?'snapshot audit':'source refresh',sourcePagesPinned:JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/coverage-provenance.json'),'utf8').catch(()=>'[]')).length,verifiedAt:new Date().toISOString(),pages:0,stations:0,acquisitions:0,recipes:0,art:0,failures:[],games:{}};
 const art=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/art.json'),'utf8').catch(()=>'{"valheim":{},"dragonwilds":{},"enshrouded":{},"grounded2":{},"vrising":{}}'));
 const listing=document((await request('https://corpus.gg/games/valheim/items')).text),urls=new Map();
 listing('a[href^="/games/valheim/items/"]').each((_,a)=>urls.set(listing(a).attr('href'),true));
 // Sitemap includes items omitted from the category landing page.
 for(const u of ['https://corpus.gg/sitemap.xml','https://corpus.gg/sitemap/0.xml'])try{const t=(await request(u)).text;for(const m of t.matchAll(/<loc>(https:\/\/corpus\.gg\/games\/valheim\/items\/[^<]+)<\/loc>/g))urls.set(new URL(m[1]).pathname,true);for(const m of t.matchAll(/<loc>(https:\/\/corpus\.gg\/[^<]*sitemap[^<]*\.xml)<\/loc>/g)){const sub=(await request(m[1])).text;for(const n of sub.matchAll(/<loc>(https:\/\/corpus\.gg\/games\/valheim\/items\/[^<]+)<\/loc>/g))urls.set(new URL(n[1]).pathname,true);}}catch{}
 // Known localized item names are stable slugs; page H1 must match before applying data.
 for(const i of items)urls.set('/games/valheim/items/'+i.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),true);
 let cursor=0,count=0;const entries=[...urls.keys()];const provenance=[];
 async function worker(){while(cursor<entries.length){const route=entries[cursor++],url='https://corpus.gg'+route;try{const record=await request(url),$=document(record.text),title=$('h1').first().text().trim().replace(/\s+Quality\s+\d+$/i,'');let decoded='';for(const m of record.text.matchAll(/self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)/g))try{decoded+=JSON.parse(m[1]);}catch{}const native=decoded.match(/"nativeName":"([^"]+)"/)?.[1],existing=catalog.items.find(i=>i.id===native)||names.get(title.toLowerCase());let item=existing;if(!item&&native&&catalog.recipes.some(r=>r.inputs.some(i=>i.name.toLowerCase()===title.toLowerCase()))){item={id:native,name:title,category:'Fish',description:$('.prose p').first().text().trim(),acquisition:'',iconUrl:'',sourceUrl:url};catalog.items.push(item);items.push(item);names.set(title.toLowerCase(),item);report.addedItems=(report.addedItems||0)+1;}if(!item)continue;report.pages++;item.sourceUrl=url;provenance.push({url,fetchedAt:record.fetchedAt,sha256:hash(record.text)});
 const stationLabel=$('*').filter((_,el)=>$(el).children().length===0&&$(el).text().trim()==='Required station').first();let station=stationLabel.parent().find('a[href*="/building/"]').first().text().trim();let stationData;try{stationData=JSON.parse(decoded.match(/"stations":(.*?),"initialQuality"/)?.[1]);}catch{}if(!station&&stationData?.length)station=stationData[0].entity.name;
 
 const sections=$('h2').map((_,h)=>({title:$(h).text().trim(),node:$(h).parent()})).get(),source=[];if(!sections.some(s=>s.title==='Crafting recipe'||s.title==='Upgrade-only recipe')){const inactive=catalog.recipes.filter(r=>r.id.startsWith('Recipe_')&&r.outputs.some(o=>o.itemId===item.id));for(const recipe of inactive)if(!retired.some(v=>v.recipe.id===recipe.id))retired.push({recipe,reason:'No active ordinary or upgrade-only recipe on the current source item page',sourceUrl:url});catalog.recipes=catalog.recipes.filter(r=>!inactive.includes(r));if(inactive.length){delete upgrades[item.id];report.inactiveRecipes=(report.inactiveRecipes||0)+inactive.length;}}if(!station&&stationData?.length===0&&sections.some(s=>s.title==='Crafting recipe'))station='Handcrafting (inventory)';if(sections.some(s=>s.title==='Upgrade-only recipe')&&!sections.some(s=>s.title==='Crafting recipe')){const removed=catalog.recipes.filter(r=>r.id.startsWith('Recipe_')&&r.outputs.some(o=>o.itemId===item.id));catalog.recipes=catalog.recipes.filter(r=>!removed.includes(r));if(removed.length)report.upgradeOnly=(report.upgradeOnly||0)+removed.length;const initial=catalog.recipes.find(r=>r.id.startsWith('Processing:')&&r.outputs.some(o=>o.itemId===item.id));if(initial&&upgrades[item.id]){upgrades[item.id].levels[0]={level:1,inputs:initial.inputs};upgrades[item.id].station=station;upgrades[item.id].initialSourceUrl=url;}}
 if(station)for(const r of catalog.recipes)if(!r.id.startsWith('Processing:')&&r.outputs.some(o=>o.itemId===item.id)){if(r.station!==station){r.station=station;r.sourceUrl=url;report.stations++;}}
 for(const s of sections)if(/^(Dropped by|Found in|May be found in|Natural gathering sources|Tree harvesting sources|Mining sources|Gathered in|Gathered from|Harvested from|Biomes|Bait|Sold by|Obtained from|Purchased from|Sold by|Source|Acquisition|Grown from|Grown at|Farming)/i.test(s.title)){const details=s.node.find('li').map((_,x)=>$(x).find('a').first().text().trim()||$(x).text().replace(/\s+/g,' ').trim()).get();s.node.find('tbody tr').each((_,tr)=>{const cells=$(tr).find('td'),name=cells.eq(0).text().trim();if(name)details.push(name);});if(details.length)source.push(s.title+': '+[...new Set(details)].join('; '));}
 if(source.length){item.acquisition=source.join('. ');report.acquisitions++;}
 for(const section of sections.filter(s=>s.title==='Crafting recipe')){const inputs=[];section.node.find('a[href*="/items/"]').each((_,a)=>{const el=$(a),qty=Number(el.find('strong').first().text().match(/×\s*(\d+)/)?.[1]),name=el.find('span').first().clone().children().remove().end().text().trim(),linked=names.get(name.toLowerCase());if(qty&&linked)inputs.push({itemId:linked.id,name:linked.name,quantity:qty});});for(const recipe of catalog.recipes.filter(r=>r.outputs.some(o=>o.itemId===item.id)))for(const input of recipe.inputs){const anchor=section.node.find('a[href*="/items/"]').filter((_,a)=>$(a).find('span').first().clone().children().remove().end().text().trim().toLowerCase()===input.name.toLowerCase()).first();if(anchor.length)try{const linkedUrl=new URL(anchor.attr('href'),url).href,linkedRecord=await request(linkedUrl);let content='';for(const m of linkedRecord.text.matchAll(/self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)/g))try{content+=JSON.parse(m[1]);}catch{}const id=content.match(/"nativeName":"([^"]+)"/)?.[1];if(id&&catalog.items.some(i=>i.id===id))input.itemId=id;}catch{}}const amount=Number(section.node.find('p').first().text().match(/Produces\s+(\d+) unit/)?.[1]);if(inputs.length&&amount&&station&&!catalog.recipes.some(r=>r.outputs.some(o=>o.itemId===item.id))){catalog.recipes.push({id:'Corpus:'+item.id,station,notes:'Explicit initial ingredient amounts; versioned source page.',sourceUrl:url,inputs,outputs:[{itemId:item.id,name:item.name,quantity:amount}]});report.recipes++;}}
 const image=$('img[src*="/renders/"]').first().attr('src');if(image&&!art.valheim[item.id]){const key=hash(image).slice(0,24)+'.webp',target=path.join(root,'public/assets/art',key);await fs.mkdir(path.dirname(target),{recursive:true});try{await fs.access(target);}catch{const r=await fetch(image,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Art HTTP '+r.status);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>8000000)throw Error('Art too large');await sharp(bytes).trim().resize(512,512,{fit:'inside',withoutEnlargement:true}).webp({quality:88}).toFile(target);}art.valheim[item.id]='./assets/art/'+key;report.art++;}
 }catch(e){report.failures.push({url,reason:e.message});}finally{if(++count%100===0)console.log('Valheim pages checked',count,'/',entries.length);await new Promise(r=>setTimeout(r,200));}}}
 if(!process.argv.includes('--report-only'))await Promise.all([worker(),worker(),worker()]);
 if(!process.argv.includes('--report-only')){catalog.importedAt=new Date().toISOString();catalog.coverage=catalog.coverage.replace(/ Item pages audited[\s\S]*$/,'');catalog.coverage+=' Item pages audited against Corpus 1.0.12 for required stations, initial recipes, acquisition relationships and full item renders. Unknown sources remain explicitly incomplete.';
 await fs.writeFile(path.join(root,'src/catalog/data/valheim-inactive-recipes.json'),JSON.stringify(retired,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/valheim-upgrades.json'),JSON.stringify(upgrades,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/valheim.json'),JSON.stringify(catalog,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/art.json'),JSON.stringify(art,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/coverage-provenance.json'),JSON.stringify(provenance,null,2)+'\n');
 }
 for(const game of ['valheim','dragonwilds','enshrouded','grounded2','vrising']){const c=game==='valheim'?catalog:JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/'+game+'.json'),'utf8')),idx=indexCatalog(c),unique=canonicalItems(c),missing=[];let trees=0,alternatives=0;const treeWarnings=[];for(const i of unique){const recipes=idx.recipes.get('i:'+i.id)||[];if(!recipes.length&&!i.acquisition)missing.push({id:i.id,name:i.name,category:i.category,sourceUrl:i.sourceUrl});if(recipes.length)try{buildShoppingList({id:'audit',game,targets:[{itemId:i.id,name:i.name,quantity:1}],recipes:{},progress:{},owned:{},useSupplies:false,collapsed:{},hideCompleted:false},c);trees++;for(const choice of recipes){const r=buildShoppingList({id:'audit',game,targets:[{itemId:i.id,name:i.name,quantity:1}],recipes:{['i:'+i.id]:choice.recipe.id},progress:{},owned:{},useSupplies:false,collapsed:{},hideCompleted:false},c);alternatives++;if(r.warnings.length)treeWarnings.push({item:i.id,recipe:choice.recipe.id,warnings:r.warnings});}}catch(e){report.failures.push({game,item:i.id,reason:e.message});}}
 report.games[game]={items:unique.length,recipes:c.recipes.length,recipeTreesChecked:trees,alternativeTreesChecked:alternatives,treeWarnings,missingStations:c.recipes.filter(r=>!r.station).map(r=>r.id),unresolvedInputs:c.recipes.flatMap(r=>r.inputs.filter(i=>!idx.resolve(i)).map(i=>({recipe:r.id,input:i.name}))),missingAcquisition:missing};}
 await fs.writeFile(path.join(root,'src/catalog/data/coverage-audit.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,failures:report.failures.length,games:Object.fromEntries(Object.entries(report.games).map(([g,v])=>[g,{...v,treeWarnings:v.treeWarnings.length,missingStations:v.missingStations.length,unresolvedInputs:v.unresolvedInputs.length,missingAcquisition:v.missingAcquisition.length}]))},null,2));}
if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=1;});
