const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),sharp=require('sharp');
const {clean,recipes}=require('./dune-parse.cjs');
const root=path.resolve(__dirname,'../..'),cache=path.join(root,'.catalog-cache'),base='https://awakening.wiki';
const hash=s=>crypto.createHash('sha256').update(s).digest('hex'),provenance=[];
async function request(url){const file=path.join(cache,hash(url)+'.json');let r;try{r=JSON.parse(await fs.readFile(file,'utf8'));}catch{const response=await fetch(url,{headers:{'User-Agent':'BancyCraft noncommercial offline catalog; https://github.com/d-bergman/bancycraft'},signal:AbortSignal.timeout(45000)});if(!response.ok)throw Error('Source HTTP '+response.status);r={url,fetchedAt:new Date().toISOString(),text:await response.text()};await fs.writeFile(file,JSON.stringify(r));}provenance.push({url,fetchedAt:r.fetchedAt,sha256:hash(r.text)});return JSON.parse(r.text);}
const pageUrl=n=>base+'/'+encodeURIComponent(n.replace(/ /g,'_'));
function category(v){const t=v.item_tags||'';if(/Schematics/.test(t))return 'Schematic';if(v.equip_slot)return ({Head:'Helmet',Torso:'Chest armor',Hands:'Gloves',Feet:'Boots',Legs:'Leg armor'})[v.equip_slot]||'Armor '+v.equip_slot;if(v.weapon_type)return 'Weapon '+(v.melee_weapon_type||v.weapon_type);if(/RawResources|CraftingResources|Components/.test(t))return 'Material';if(/Ammo|Ammunition/.test(t))return 'Ammunition';if(/Consumables/.test(t))return 'Consumable';if(/Contracts/.test(t))return 'Quest item';if(v.vehicle_module_type)return 'Vehicle component';if(v.utility_type)return 'Utility '+v.utility_type;return clean(t.match(/Items\.([^" ,]+)/)?.[1]?.replace(/\./g,' '))||'Item';}
async function run(){
 const rows=[];for(let offset=0;;offset+=1000){const data=await request('https://api.awakening.wiki/items?limit=1000&offset='+offset);rows.push(...data.list);if(data.pageInfo.isLastPage)break;}
 const items=rows.filter(v=>v.item_id&&v.name).map(v=>({id:v.item_id,name:v.name,category:category(v),description:clean(v.long_description||v.short_description),acquisition:'',sourceUrl:pageUrl(v.name)}));
 items.push({id:'water-ml',name:'Water (mL)',category:'Material',description:'Water volume in milliliters; recipe water costs are not item counts.',acquisition:'',sourceUrl:pageUrl('Water')});
 const byId=new Map(items.map(i=>[i.id,i])),byName=new Map(items.map(i=>[i.name.toLowerCase(),i])),pages=new Map(),failures=[];
 async function readPages(titles){for(let p=0;p<titles.length;p+=40){const data=await request(base+'/api.php?'+new URLSearchParams({action:'query',titles:titles.slice(p,p+40).join('|'),prop:'revisions',rvprop:'ids|timestamp|content',rvslots:'main',format:'json',redirects:'1'}));for(const v of Object.values(data.query?.pages||{}))if(v.revisions?.length)pages.set(v.title,v);for(const redirect of [...(data.query?.redirects||[]),...(data.query?.normalized||[])])if(pages.has(redirect.to))pages.set(redirect.from,pages.get(redirect.to));if(p%400===0)console.log('Dune pages',p,'/',titles.length);await new Promise(r=>setTimeout(r,180));}}
 await readPages([...new Set([...items.map(i=>i.name==='Water (mL)'?'Water':i.name)])]);

 // Resolve explicit wiki resources omitted from the public item API. Native keys
 // are aliases only; persisted IDs belong to the verified named wiki page.
 const extras={'PlantFiber':'Plant Fiber','SpiceSand':'Spice Sand','SolarisCoin':'Solari','Thumper':'Thumper','Stilltent':'Stilltent','UniqueThumper_03':'Improved Thumper','UniqueThumper_02':'Enhanced Thumper','WeldingMaterial3':'Vehicle Welding Wire','WeldingMaterial5':'Advanced Vehicle Welding Wire'};
 const unknownNames=new Set(Object.values(extras));for(const p of new Set(pages.values()))for(const m of p.revisions[0].slots.main['*'].matchAll(/\[\[([^\]|]+)\]\]\s*x\d+|\{\{Icon\|([^|}]+)\|amount=/g)){const n=(m[1]||m[2]).trim();if(!byId.has(n)&&!byName.has(n.toLowerCase())&&!/^(time|Water)$/.test(n))unknownNames.add(n);}
 await readPages([...unknownNames].filter(n=>!pages.has(n)));
 for(const n of unknownNames){const p=pages.get(n);if(!p||byName.has(n.toLowerCase()))continue;const text=p.revisions[0].slots.main['*'];if(!/Infobox|ITEMID|ItemInfo/.test(text))continue;const intro=clean(text.replace(/<!--[^]*?-->/g,'').replace(/\{\{[^]*?\}\}/g,'').split(/^==/m)[0]);const native=text.match(/item_id\s*=\s*([^|}\s]+)/i)?.[1]||text.match(/\|ITEMID\|([^|]+)\|ITEMID\|/)?.[1];const id=native||'Wiki:'+p.title;if(byId.has(id)){byName.set(n.toLowerCase(),byId.get(id));continue;}const item={id,name:p.title,category:'Material',description:intro,acquisition:'',sourceUrl:pageUrl(p.title)};items.push(item);byId.set(id,item);byName.set(n.toLowerCase(),item);byName.set(p.title.toLowerCase(),item);}
 for(const [key,name]of Object.entries(extras)){const item=byName.get(name.toLowerCase());if(item)byId.set(key,item);}
 byName.set('water',byId.get('water-ml'));for(const item of items){const p=pages.get(item.name);const native=p?.revisions[0].slots.main['*'].match(/item_id\s*=\s*([^|}\s]+)/i)?.[1];if(native&&byId.has(native))byName.set(item.name.toLowerCase(),byId.get(native));}
 const parsed=[],rejected=[],stations=new Set();
 function parsePage(title,p){const text=p.revisions[0].slots.main['*'],x=recipes(text,title,byId,byName);parsed.push(...x.result.map(r=>({...r,sourceUrl:pageUrl(title)})));rejected.push(...x.rejected);for(const r of x.result)stations.add(r.station);}
 for(const item of items){const p=pages.get(item.name==='Water (mL)'?'Water':item.name);if(!p){item.sourceUrl='https://api.awakening.wiki/items?'+new URLSearchParams({where:'(item_id,eq,'+item.id+')'});failures.push({item:item.id,reason:'No wiki page revision; public API is the item provenance'});continue;}item.revision=p.revisions[0].revid;item.updatedAt=p.revisions[0].timestamp;const text=p.revisions[0].slots.main['*'];parsePage(p.title,p);const intro=clean(text.replace(/<!--[^]*?-->/g,'').replace(/\{\{[^]*?\}\}/g,'').split(/^==/m)[0]);const sourceSections=[...text.matchAll(/^==\s*(Obtainment|Obtaining|Acquisition|Locations?|Sources?|In-Game)\s*==\s*([^]*?)(?=^==[^=]|$(?![^]))/gmi)].map(m=>clean(m[2]));if(sourceSections.length)item.acquisition=sourceSections.join('. ').slice(0,1800);else if(/\b(found|gathered|harvested|obtained|looted|purchased|sold by|dropped by|collected|mined|scavenged|picked)\b/i.test(intro))item.acquisition=intro.slice(0,1800);}
 await readPages([...stations].filter(t=>!pages.has(t)));for(const t of stations){const p=pages.get(t);if(p)parsePage(t,p);}
 const unique=new Map();for(const r of parsed){const key=JSON.stringify([r.station,r.inputs,r.outputs]);if(!unique.has(key))unique.set(key,{id:'DACW:'+hash(key).slice(0,24),...r,notes:'Source base costs. Water quantities are mL. Unique schematics and unlock prerequisites may still be required; loot yields are not inferred.'});}
 const catalog={schemaVersion:1,game:'duneawakening',importedAt:new Date().toISOString(),source:{name:'Dune: Awakening Community Wiki',url:base+'/',license:'CC BY-NC-SA 4.0 (adapted wiki/API data); game materials © Funcom Oslo AS',licenseUrl:'https://creativecommons.org/licenses/by-nc-sa/4.0/',version:'API snapshot '+new Date().toISOString().slice(0,10)},coverage:'Public item API and explicit Crafted By/Recipes tables. Exact station alternatives and water mL preserved. Unsupported or unresolved rows are excluded and audited. Descriptions are not treated as acquisition unless explicitly stated. Community data is incomplete; unknown sources and unlock requirements are not invented.',items:items.sort((a,b)=>a.name.localeCompare(b.name)),recipes:[...unique.values()]};
 await fs.writeFile(path.join(root,'src/catalog/data/duneawakening.json'),JSON.stringify(catalog,null,2)+'\n');
 const gearsets=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/gearsets.json'),'utf8')),families=new Map();for(const row of rows.filter(v=>v.garment_type&&v.equip_slot)){const item=byId.get(row.item_id);const name=item.name.replace(/\s+(?:Helmet|Mask|Hood|Gloves|Gauntlets|Boots|Shoes|Chestplate|Jacket|Shirt|Pants|Leggings|Trousers)$/i,'');if(name===item.name)continue;const family=families.get(name)||[];family.push(item.id);families.set(name,family);}const crafted=new Set(catalog.recipes.flatMap(r=>r.outputs.map(o=>o.itemId)));gearsets.duneawakening=[...families].filter(([,ids])=>ids.length>=3&&ids.every(id=>crafted.has(id)||byId.get(id).acquisition)).map(([name,ids])=>({name:name+' equipment bundle',ids,alternatives:{},kind:'Equipment bundle',sourceUrl:byId.get(ids[0]).sourceUrl}));await fs.writeFile(path.join(root,'src/catalog/data/gearsets.json'),JSON.stringify(gearsets,null,2)+'\n');
 const icons=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/icons.json'),'utf8')),art=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/art.json'),'utf8'));icons.duneawakening={};art.duneawakening={};
 const imageNames=[...new Set(rows.map(v=>v.image).filter(Boolean))],urls=new Map();for(let p=0;p<imageNames.length;p+=40){const data=await request(base+'/api.php?'+new URLSearchParams({action:'query',titles:imageNames.slice(p,p+40).map(n=>'File:'+n).join('|'),prop:'imageinfo',iiprop:'url',format:'json'}));for(const page of Object.values(data.query?.pages||{}))if(page.imageinfo?.[0]?.url)urls.set(page.title.slice(5).replaceAll('_',' '),page.imageinfo[0].url);}
 let cursor=0;async function worker(){while(cursor<rows.length){const row=rows[cursor++],url=urls.get(row.image?.replaceAll('_',' '));if(!url)continue;try{const u=new URL(url);if(u.protocol!=='https:'||!/(?:^|\.)awakening\.wiki$/.test(u.hostname))throw Error('Unexpected image host');const file=hash(url).slice(0,24)+'.webp',target=path.join(root,'public/assets/items',file);try{await fs.access(target);}catch{const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('Image HTTP '+r.status);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>8000000)throw Error('Image too large');await sharp(bytes).resize(256,256,{fit:'inside',withoutEnlargement:true}).webp({quality:86}).toFile(target);}icons.duneawakening[row.item_id]='./assets/items/'+file;}catch(e){failures.push({image:row.image,reason:e.message});}}}await Promise.all([worker(),worker(),worker()]);
 await fs.writeFile(path.join(root,'src/catalog/data/icons.json'),JSON.stringify(icons,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/art.json'),JSON.stringify(art,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/dune-import-audit.json'),JSON.stringify({importedAt:catalog.importedAt,items:items.length,recipes:catalog.recipes.length,icons:Object.keys(icons.duneawakening).length,sets:gearsets.duneawakening.length,rejected,failures,provenance},null,2)+'\n');console.log('DUNE_IMPORTED',items.length,catalog.recipes.length,Object.keys(icons.duneawakening).length,'rejected',rejected.length,'failures',failures.length);
}
if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=1;});
module.exports={category};
