const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),sharp=require('sharp');
const {templates,plain,quantity}=require('./parse.cjs'),root=path.resolve(__dirname,'../..'),cache=path.join(root,'.catalog-cache');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const bases={dragonwilds:'https://dragonwilds.runescape.wiki',enshrouded:'https://enshrouded.wiki.gg',grounded2:'https://grounded.wiki.gg',vrising:'https://wiki.v-ris.ing'};
async function request(url){const file=path.join(cache,hash(url)+'.json');try{return JSON.parse(await fs.readFile(file,'utf8'));}catch{}await new Promise(r=>setTimeout(r,200));const r=await fetch(url,{headers:{'User-Agent':'BancyCraft/0.8.0 source and artwork audit; https://github.com/d-bergman/bancycraft'},signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error('Source HTTP '+r.status);const record={url,fetchedAt:new Date().toISOString(),text:await r.text()};await fs.writeFile(file,JSON.stringify(record));return record;}
function readable(raw,title){return plain(raw.replace(/\{\{(?:item\+iconright|item|icon|quest\+the|item\+icon)\|([^|}]+)[^}]*\}\}/gi,'$1'),title).replace(/^[*#]\s*/gm,'').trim();}
async function run(){const {indexCatalog}=await import('../../src/planner/engine.mjs'),art=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/art.json'),'utf8'));const records=[];
 for(const f of await fs.readdir(cache))try{const r=JSON.parse(await fs.readFile(path.join(cache,f),'utf8'));if(r.url?.includes('rvprop'))records.push(r);}catch{}
 const report={verifiedAt:new Date().toISOString(),games:{},failures:[]};
 for(const [game,base] of Object.entries(bases)){const catalog=JSON.parse(await fs.readFile(path.join(root,'src/catalog/data/'+game+'.json'),'utf8')),byName=new Map(catalog.items.map(i=>[i.name.toLowerCase(),i])),pages=new Map(),images=new Map();let sources=0,recipes=0,aliases=0,artCount=0;
 for(const record of records)if(record.url.startsWith(base+'/'))try{for(const p of Object.values(JSON.parse(record.text).query.pages||{}))if(p.revisions?.[0])pages.set(p.title,p);}catch{}
 const unresolved=[...new Set(catalog.recipes.flatMap(r=>r.inputs.filter(i=>!indexCatalog(catalog).resolve(i)).map(i=>i.name)))].filter(n=>! /^Any /i.test(n));
 for(let offset=0;offset<unresolved.length;offset+=50)try{const record=await request(base+'/api.php?'+new URLSearchParams({action:'query',titles:unresolved.slice(offset,offset+50).join('|'),redirects:'1',prop:'revisions',rvprop:'ids|timestamp|content',rvslots:'main',format:'json'})),data=JSON.parse(record.text);for(const p of Object.values(data.query?.pages||{}))if(p.revisions?.[0])pages.set(p.title,p);for(const r of [...(data.query?.normalized||[]),...(data.query?.redirects||[])]){const match=byName.get(r.to.toLowerCase());if(match)for(const recipe of catalog.recipes)for(const input of recipe.inputs)if(input.name===r.from){input.itemId=match.id;aliases++;}}}catch(e){report.failures.push({game,stage:'aliases',reason:e.message});}
 for(const [title,page] of pages){const item=byName.get(title.toLowerCase());if(!item)continue;let text=page.revisions[0].slots.main['*'];const boxes=templates(text),box=game==='grounded2'?boxes.find(t=>/infobox/.test(t.name)&&/\/g2$/.test(t.name)):boxes.find(t=>/infobox/.test(t.name));
 if(game==='grounded2'&&!box)continue;
 const scoped=game==='grounded2'?text.slice(box.start).split(/\n\|-\|/)[0]:text;
 const info=game==='grounded2'?[box]:boxes,sourceFields=info.flatMap(t=>['source','location','obtaining','obtained from'].map(k=>t.fields[k])).filter(Boolean);
 const sections=[...scoped.matchAll(/^==\s*(Obtaining|Source|Sources|How to Obtain|Acquisition|Location|Locations)\s*==\s*([\s\S]*?)(?=^==[^=]|$(?![\s\S]))/gmi)].map(m=>m[2]);
 const value=[...sourceFields,...sections].map(v=>readable(v,title)).filter(Boolean).join('. ').slice(0,1800);if(value&&value!==item.acquisition){item.acquisition=value;sources++;}
 for(const [n,t] of boxes.filter(t=>t.name==='crafting').entries()){const f=t.fields,inputs=(f.ingredients||'').split(',').map(part=>{const m=part.trim().match(/^(.+):\s*(\d+)$/);if(!m)return null;const name=plain(m[1]).replace(/^:/,''),found=byName.get(name.toLowerCase());return {name,quantity:Number(m[2]),...(found?{itemId:found.id}:{})};}),amount=quantity(f['crafted quantity'],1);if(!amount||!inputs.length||inputs.some(i=>!i||!i.quantity))continue;const station=plain(f.crafter||f.workshop),existing=catalog.recipes.some(r=>r.outputs.some(o=>o.name===item.name)&&r.station===station&&r.inputs.length===inputs.length&&r.inputs.every(i=>inputs.some(x=>x.name===i.name&&x.quantity===i.quantity)));if(!existing&&station){catalog.recipes.push({id:'Audit:'+title+':'+n,station,notes:'Explicit item-page Crafting template.',inputs,outputs:[{itemId:item.id,name:item.name,quantity:amount}],sourceUrl:item.sourceUrl});recipes++;}}
 const field=box?.fields.image||box?.fields.images||title+'.png';const file=field.replace(/\{\{(?:SUB)?PAGENAME\}\}/gi,title).split(',')[0].replace(/^File:/i,'').trim();if(file&&! /[{}|]/.test(file)&&/weapon|sword|axe|mace|hammer|bow|wand|staff|spear|dagger|armor|armour|helmet|chest|legs|cape|shoulder|head|body|boots|gloves|equipment|food|potion|consum|trinket|smoothie/i.test(item.category+' '+item.name))images.set(item.id,file);
 }
 // Strip malformed leading namespace punctuation only when the real item is unique.
 for(const recipe of catalog.recipes)for(const input of recipe.inputs){const match=byName.get(input.name.replace(/^:/,'').toLowerCase());if(!input.itemId&&match){input.itemId=match.id;aliases++;}}
 const names=[...new Set(images.values())],urls=new Map();for(let offset=0;offset<names.length;offset+=50)try{const record=await request(base+'/api.php?'+new URLSearchParams({action:'query',titles:names.slice(offset,offset+50).map(n=>'File:'+n).join('|'),prop:'imageinfo',iiprop:'url',format:'json',redirects:'1'})),data=JSON.parse(record.text);for(const p of Object.values(data.query?.pages||{}))if(p.imageinfo?.[0])urls.set(p.title.replace(/^File:/,'').replaceAll('_',' '),p.imageinfo[0].url);for(const r of data.query?.redirects||[])if(urls.has(r.to.replace(/^File:/,'').replaceAll('_',' ')))urls.set(r.from.replace(/^File:/,'').replaceAll('_',' '),urls.get(r.to.replace(/^File:/,'').replaceAll('_',' ')));}catch(e){report.failures.push({game,stage:'art-metadata',reason:e.message});}
 let cursor=0;const entries=[...images];async function worker(){while(cursor<entries.length){const [id,name]=entries[cursor++],url=urls.get(name.replaceAll('_',' '));if(!url||art[game][id])continue;try{const key=hash(url).slice(0,24)+'.webp',target=path.join(root,'public/assets/art',key);try{await fs.access(target);}catch{const r=await fetch(url,{signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error('Art HTTP '+r.status);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>8000000)throw Error('Art too large');await sharp(bytes).trim().resize(512,512,{fit:'inside',withoutEnlargement:true}).webp({quality:88}).toFile(target);}art[game][id]='./assets/art/'+key;artCount++;await new Promise(r=>setTimeout(r,200));}catch(e){report.failures.push({game,item:id,stage:'art',reason:e.message});}}}await Promise.all([worker(),worker()]);
 catalog.importedAt=new Date().toISOString();await fs.writeFile(path.join(root,'src/catalog/data/'+game+'.json'),JSON.stringify(catalog,null,2)+'\n');await fs.writeFile(path.join(root,'src/catalog/data/art.json'),JSON.stringify(art,null,2)+'\n');report.games[game]={sources,recipes,aliases,art:artCount};console.log(game,report.games[game]);}
 await fs.writeFile(path.join(root,'src/catalog/data/wiki-details-audit.json'),JSON.stringify(report,null,2)+'\n');}
if(require.main===module)run().catch(e=>{console.error(e.message);process.exitCode=1;});
