import {useState} from 'react';
import {Plus,Search,Check} from 'lucide-react';
import {Dialog} from '../ui/Dialog';
import {catalogs} from '../catalog/catalogs';
import {ItemIcon} from '../catalog/ItemIcon';
import {canonicalItems,broadType,indexCatalog} from './engine.mjs';
import type {Game,ListTarget} from '../types';
export function AddItemsDialog({game,busy,onAdd,onClose}:{game:Game;busy:boolean;onAdd:(targets:ListTarget[])=>Promise<boolean>;onClose:()=>void}) {
 const [query,setQuery]=useState(''),[type,setType]=useState('All items'),[subtype,setSubtype]=useState('All item types'),[page,setPage]=useState(0),[quantities,setQuantities]=useState<Record<string,number>>({}),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(''),[pending,setPending]=useState(false);
 const catalog=catalogs[game],index=indexCatalog(catalog),all=canonicalItems(catalog),categories=[...new Set(all.map(i=>i.category))].sort(),types=[...new Set(all.map(i=>broadType(i)))].sort();
 const items=all.filter(i=>i.name.toLowerCase().includes(query.toLowerCase())&&(type==='All items'||broadType(i)===type)&&(subtype==='All item types'||i.category===subtype)).sort((a,b)=>a.name.localeCompare(b.name));
 const current=Math.min(page,Math.max(0,Math.ceil(items.length/20)-1));
 async function add(ids:string[]){if(busy||pending)return;setPending(true);try{const targets=ids.map(id=>{const item=index.byId.get(id)!;return {itemId:id,name:item.name,quantity:quantities[id]||1};});if(await onAdd(targets)){setNotice(targets.length+' item'+(targets.length===1?'':'s')+' added to this list.');setSelected([]);}else setNotice('Could not add items. Check your connection or list limits and try again.');}catch(e){setNotice(e instanceof Error?e.message:'Could not add items.');}finally{setPending(false);}}
 return <Dialog title="Add items to this list" onClose={onClose}><div className="actions"><label>Type<select aria-label="List item type" value={type} onChange={e=>{setType(e.target.value);setPage(0);}}><option>All items</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Item type<select aria-label="List item category" value={subtype} onChange={e=>{setSubtype(e.target.value);setPage(0);}}><option>All item types</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><label className="catalog-search"><Search size={17}/><input autoFocus aria-label="Search items for this list" value={query} placeholder="Search this game’s items…" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>{notice&&<p role="status"><Check size={15}/>{notice}</p>}{selected.length>0&&<button className="button primary" disabled={busy||pending} onClick={()=>add(selected)}><Plus size={16}/>Add {selected.length} selected</button>}<div className="list-add-results">{items.slice(current*20,current*20+20).map(i=><article key={i.id}><input type="checkbox" aria-label={'Select '+i.name} checked={selected.includes(i.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,i.id]:v.filter(x=>x!==i.id))}/><ItemIcon game={game} id={i.id}/><span><strong>{i.name}</strong><small>{i.category}</small></span><input type="number" aria-label={'Add quantity '+i.name} value={quantities[i.id]||1} min={1} max={999999} onChange={e=>{const n=Number(e.target.value);if(Number.isSafeInteger(n)&&n>0&&n<=999999)setQuantities(q=>({...q,[i.id]:n}));}}/><button className="icon-button" title="Add to this list" aria-label={'Add '+i.name+' to this list'} disabled={busy||pending} onClick={()=>add([i.id])}><Plus size={18}/></button></article>)}</div><div className="numbered-pagination"><button className="button outline" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{items.length} items · Page {current+1} of {Math.max(1,Math.ceil(items.length/20))}</span><button className="button outline" disabled={(current+1)*20>=items.length} onClick={()=>setPage(current+1)}>Next</button></div></Dialog>;
}
