import { useEffect, useLayoutEffect, useRef, useState, type PointerEvent } from 'react';
import { ExternalLink, Hammer, Minus, Plus, RotateCcw } from 'lucide-react';
import type { ShoppingList } from '../types';
import { catalogs } from '../catalog/catalogs';
import { ItemIcon } from '../catalog/ItemIcon';
import { Dialog } from '../ui/Dialog';
import { api } from '../bridge';
import type { ShoppingRow } from './engine.mjs';
import { buildCraftingTree } from './tree.mjs';
import './tree.css';

export function CraftingTree({ list, row, onClose }: { list: ShoppingList; row: ShoppingRow; onClose: () => void }) {
  const [quantity, setQuantity] = useState(row.required), [selected, setSelected] = useState('root'), [linkError, setLinkError] = useState(''), [zoom,setZoom]=useState(1);
  const scroller=useRef<HTMLDivElement>(null);
  const drag=useRef<{id:number;x:number;y:number;left:number;top:number;moved:boolean}|null>(null);
  const suppressClick=useRef(false);
  const zoomAnchor=useRef<{x:number;y:number;contentX:number;contentY:number}|null>(null);
  const [dragging,setDragging]=useState(false);
  let tree: ReturnType<typeof buildCraftingTree> | undefined, error = '';
  try { tree = buildCraftingTree(list, catalogs[list.game], row, quantity); } catch (e) { error = e instanceof Error ? e.message : 'Unable to build this recipe tree.'; }
  useEffect(()=>{const frame=requestAnimationFrame(()=>{const view=scroller.current;if(view&&tree){const root=tree.nodes[0];view.scrollLeft=Math.max(0,(root.x+90)*zoom-view.clientWidth/2);view.scrollTop=0;}});return()=>cancelAnimationFrame(frame);},[tree?.width,quantity,row.key]);
  useLayoutEffect(()=>{const view=scroller.current,anchor=zoomAnchor.current;if(!view||!anchor||!tree)return;const inset=Math.max(0,(view.clientWidth-tree.width*zoom)/2);view.scrollLeft=anchor.contentX*zoom+inset-anchor.x;view.scrollTop=anchor.contentY*zoom-anchor.y;zoomAnchor.current=null;},[zoom]);
  function changeZoom(next:number,clientX?:number,clientY?:number){const view=scroller.current;if(!view||!tree)return;next=Math.max(0.25,Math.min(2,Math.round(next*100)/100));if(next===zoom)return;const rect=view.getBoundingClientRect(),x=(clientX??rect.left+rect.width/2)-rect.left,y=(clientY??rect.top+rect.height/2)-rect.top,inset=Math.max(0,(view.clientWidth-tree.width*zoom)/2);zoomAnchor.current={x,y,contentX:(view.scrollLeft+x-inset)/zoom,contentY:(view.scrollTop+y)/zoom};setZoom(next);}
  useEffect(()=>{const view=scroller.current;if(!view||!tree)return;const wheel=(event:WheelEvent)=>{event.preventDefault();const delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?view.clientHeight:1);changeZoom(zoom*Math.exp(-delta*0.0015),event.clientX,event.clientY);};view.addEventListener('wheel',wheel,{passive:false});return()=>view.removeEventListener('wheel',wheel);},[zoom,tree?.width,row.key]);
  function pointerDown(e:PointerEvent<HTMLDivElement>){if(e.button!==0||e.pointerType==='touch')return;const view=scroller.current;if(!view)return;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,left:view.scrollLeft,top:view.scrollTop,moved:false};suppressClick.current=false;}
  function pointerMove(e:PointerEvent<HTMLDivElement>){const start=drag.current,view=scroller.current;if(!start||!view||start.id!==e.pointerId)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(!start.moved&&Math.hypot(dx,dy)<4)return;if(!start.moved){start.moved=true;view.setPointerCapture(e.pointerId);setDragging(true);}view.scrollLeft=start.left-dx;view.scrollTop=start.top-dy;}
  function pointerEnd(e:PointerEvent<HTMLDivElement>){const start=drag.current;if(!start||start.id!==e.pointerId)return;suppressClick.current=start.moved;drag.current=null;if(scroller.current?.hasPointerCapture(e.pointerId))scroller.current.releasePointerCapture(e.pointerId);setDragging(false);}
  const detail = tree?.nodes.find(node => node.row.key === selected)?.row ?? tree?.nodes[0]?.row;
  return <Dialog title={'Crafting tree · '+row.name} onClose={onClose}><div className="recipe-tree">
    <div className="tree-controls"><label>Quantity to make<input aria-label="Crafting tree quantity" type="number" min="1" max="999999" value={quantity} onChange={e => setQuantity(Number(e.target.value))}/></label><button className="button outline" onClick={() => setQuantity(row.recipe ? row.output : 1)}>One recipe batch</button></div>
    <p className="small muted">Uses your list's selected recipes. Every ingredient appears beneath the craft that needs it; shared ingredients may appear on more than one branch. Your shopping list combines their totals. No creature or harvest counts are estimated.</p>
    {error && <p role="alert">{error}</p>}{tree && <><div className="tree-zoom" aria-label="Crafting tree zoom"><button className="icon-button" aria-label="Zoom out" disabled={zoom<=0.25} onClick={()=>changeZoom(zoom-0.25)}><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" disabled={zoom>=2} onClick={()=>changeZoom(zoom+0.25)}><Plus size={16}/></button><button className="icon-button" aria-label="Reset zoom" onClick={()=>changeZoom(1)}><RotateCcw size={15}/></button><button className="button outline tree-fit" onClick={()=>changeZoom(Math.max(0.25,Math.min(1,(scroller.current?.clientWidth||900)/tree.width)))}>Fit width</button><small>Scroll to zoom · drag to pan</small></div><div className={'tree-scroll'+(dragging?' is-dragging':'')} ref={scroller} tabIndex={0} aria-label="Scrollable crafting tree" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onClickCapture={e=>{if(suppressClick.current){e.stopPropagation();e.preventDefault();suppressClick.current=false;}}}><div style={{width:tree.width*zoom,height:tree.height*zoom,marginInline:'auto'}}><div className="tree-canvas" style={{width:tree.width,height:tree.height,transform:`scale(${zoom})`,transformOrigin:'top left'}}>
      <svg width={tree.width} height={tree.height} aria-hidden="true">{tree.edges.map(({from,to}) => <path key={from.row.key+'>'+to.row.key} d={`M ${from.x+90} ${from.y+108} V ${from.y+133} H ${to.x+90} V ${to.y}`} />)}</svg>
      {tree.nodes.map(({row: node,x,y}) => <button key={node.key} className={'tree-node '+(node.key===detail?.key?'selected':'')} style={{left:x,top:y}} aria-label={`${node.name}: ${node.required} needed${node.recipe ? ', '+(node.recipe.station || 'Station unknown') : ', acquire material'}`} onClick={() => setSelected(node.key)}><span className="tree-node-title"><ItemIcon game={list.game} id={node.item?.id}/><strong>{node.name}</strong></span><span className="tree-node-quantity">× {node.required.toLocaleString()} needed</span><small>{node.recipe ? node.recipe.station || 'Station unknown' : 'Acquire material'}</small></button>)}
    </div></div></div>{tree.warnings.map(w => <p className="notice compact" key={w}>{w}</p>)}</>}
    {detail && <section className="tree-detail" aria-label="Selected tree item"><h3>{detail.name}</h3>{detail.recipe ? <><p><Hammer size={16}/> {detail.recipe.station || 'Station not recorded'} · {Math.ceil(detail.required / detail.output).toLocaleString()} recipe batches · {detail.output} per batch</p><p className="tree-inputs">Per batch: {detail.recipe.inputs.map(i => `${i.quantity} ${i.name}`).join(' + ')} → {detail.recipe.outputs.map(i => `${i.quantity} ${i.name}`).join(' + ')}</p>{detail.recipe.notes && <p className="small muted">{detail.recipe.notes}</p>}{Math.ceil(detail.required/detail.output)*detail.output>detail.required && <p className="small muted">Batch rounding produces {Math.ceil(detail.required/detail.output)*detail.output-detail.required} extra {detail.name}; extras are not counted as inventory.</p>}</> : <p>{detail.item?.acquisition || 'Acquisition details are not imported. Check the item source; creature and harvest yields are not estimated.'}</p>}<button className="text-button" onClick={async()=>{try{await api.openSource(detail.recipe?.sourceUrl || detail.item?.sourceUrl || catalogs[list.game].source.url);setLinkError('');}catch{setLinkError('Unable to open the source.');}}}>View recipe / item source <ExternalLink size={14}/></button>{linkError && <p role="alert">{linkError}</p>}</section>}
  </div></Dialog>;
}
