const {_electron:electron}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),profile=path.join(root,'test-results','ledger-profile-'+Date.now()),keyFile=profile+'.key.txt';
const issued=spawnSync(process.execPath,[path.join(root,'scripts/access-keys.cjs'),'issue','Integration test','1',keyFile],{encoding:'utf8'});if(issued.status!==0)throw Error('Test key issuance failed.');
const token=fs.readFileSync(keyFile,'utf8').trim();
const env={...process.env,BANCYCRAFT_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;
async function launch(){const app=await electron.launch({executablePath:process.argv[2]||require('electron'),args:process.argv[2]?[]:[root],env});const page=await app.firstWindow();await page.getByRole('heading',{name:'Your next build starts here.'}).waitFor();return{app,page};}
(async()=>{let run=await launch();const errors=[];try{
  run.page.on('pageerror',e=>errors.push(e.message));
  assert.equal(await run.page.getByRole('navigation',{name:'Connected features'}).count(),0);
  const denial=await run.page.evaluate(()=>window.bancy.openBank().then(()=>false).catch(()=>true));assert.equal(denial,true,'IPC blocks bank before any key');
  await run.page.context().setOffline(true);
  await run.page.getByRole('button',{name:'Production Ledger',exact:true}).click();
  const frame=run.page.frameLocator('iframe[title="Dragonwilds production tools"]');
  await frame.locator('#profitInput').fill('3384');
  assert.equal(await frame.locator('#profitNet').innerText(),'50,760');
  assert.equal(await frame.locator('#profitSpend').innerText(),'152,280 Chit');
  assert.equal(await frame.locator('#profitGross').innerText(),'203,040 Chit');
  assert.match(await frame.locator('#profitUnitsStacks').innerText(),/34 stacks \+ 18 loose/);
  assert.match(await frame.locator('#profitUnitsStacks').innerText(),/4 purchases \(3 x 999 \+ 387\)/);
  assert.equal(await frame.locator('#tab-bank').isVisible(),false);
  await run.page.screenshot({path:path.join(root,'test-results/ledger-profit.png')});
  await frame.locator('#sendToProduction').click();await frame.locator('#tanneryCount').fill('30');
  assert.match(await frame.locator('#productionInputStacks').textContent(),/34 stacks \+ 18 loose/);
  assert.equal(await frame.locator('#productionDuration').textContent(),'18m 50s');
  await frame.locator('#tab-catalog').click();await frame.locator('#catalogSearch').fill('Dragonwolf Hide');
  assert.match(await frame.locator('#catalogRows').textContent(),/Dragonwolf Hide/);
  await frame.getByRole('button',{name:'Plan Dragonwolf Hide',exact:true}).click();await frame.locator('#selectedItemQuantity').fill('10');await frame.locator('#addOrderItem').click();
  assert.equal(await frame.locator('#orderTotalCost').textContent(),'450 Chit');
  assert.equal(await frame.locator('#requestOrderFunds').isVisible(),false);
  await run.page.getByRole('button',{name:'Settings & updates',exact:true}).click();
  await run.page.getByLabel('BancyCraft cipher key',{exact:true}).fill('not-a-key');await run.page.getByRole('button',{name:'Validate & unlock',exact:true}).click();
  await run.page.getByRole('alert').filter({hasText:'Invalid BancyCraft key'}).waitFor();
  assert.equal((await run.page.evaluate(()=>window.bancy.info())).access.unlocked,false);
  await run.page.getByLabel('BancyCraft cipher key',{exact:true}).fill(token);await run.page.getByRole('button',{name:'Validate & unlock',exact:true}).click();
  await run.page.getByRole('navigation',{name:'Connected features'}).waitFor();
  assert.ok(!fs.readFileSync(path.join(profile,'community-key.bin')).includes(token),'Key file is Windows-encrypted');
  await run.app.close();run=await launch();assert.equal((await run.page.evaluate(()=>window.bancy.info())).access.unlocked,true);
  await run.page.getByRole('button',{name:'Gearsets',exact:true}).click();await run.page.getByLabel('Search gearsets').fill('Rune');await run.page.getByLabel('Helmet for Rune armor').selectOption('20045');
  assert.match(await run.page.locator('.gearset-card').innerText(),/Runite Med Helm/);
  await run.page.getByLabel('Active game',{exact:true}).selectOption('valheim');await run.page.getByRole('button',{name:'Gearsets',exact:true}).click();
  assert.equal(await run.page.locator('.gearset-card').count(),20);assert.equal(await run.page.getByRole('button',{name:'Production Ledger',exact:true}).count(),0);assert.equal(await run.page.getByRole('button',{name:'Server Bank',exact:true}).count(),0);
  await run.page.getByLabel('Active game',{exact:true}).selectOption('enshrouded');await run.page.getByRole('button',{name:'Gearsets',exact:true}).click();assert.equal(await run.page.locator('.gearset-card').count(),82);
  await run.page.getByLabel('Gearset type').selectOption('Cosmetic');assert.ok(await run.page.locator('.gearset-card').count()>20);
  await run.page.screenshot({path:path.join(root,'test-results/gearsets-all.png')});
  await run.page.getByLabel('Active game',{exact:true}).selectOption('dragonwilds');
  await run.page.getByRole('button',{name:'Production Ledger',exact:true}).click();
  const local=run.page.frameLocator('iframe');await local.locator('#tab-catalog').click();await local.locator('#catalogSearch').fill('Dragonwolf Hide');await local.getByRole('button',{name:'Plan Dragonwolf Hide',exact:true}).click();await local.locator('#selectedItemQuantity').fill('10');await local.locator('#addOrderItem').click();
  const opened=run.app.waitForEvent('window');await local.locator('#requestOrderFunds').click();const bank=await opened;
  await bank.locator('#bankSignedOutGate').waitFor({timeout:60000});assert.equal(await bank.evaluate(()=>typeof window.bancy),'undefined');
  assert.ok(new URL(bank.url()).hostname.endsWith('bancy.gg'));
  await bank.getByText('Merchant order imported from BancyCraft.',{exact:false}).waitFor();assert.equal(await bank.locator('#bankRequestAmount').inputValue(),'450');assert.match(await bank.locator('#bankRequestNote').inputValue(),/10 Dragonwolf Hide/);
  await bank.screenshot({path:path.join(root,'test-results/bank-signed-out.png')});
  await run.page.getByRole('button',{name:'Settings & updates',exact:true}).click();await run.page.getByRole('button',{name:'Lock & remove key',exact:true}).click();
  await run.page.getByRole('navigation',{name:'Connected features'}).waitFor({state:'hidden'});assert.equal(fs.existsSync(path.join(profile,'community-key.bin')),false);assert.ok(bank.isClosed());
  assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',checks:['offline website calculations and stack/purchase regression','production timing and merchant catalog','unsigned keys and direct bank IPC denied','Windows-encrypted key persistence and removal','all game gearsets and helmet choice','game-scoped ledger/bank navigation','real signed-out website bank without native bridge','key lock closes bank']},null,2));
}catch(e){await run.page.screenshot({path:path.join(root,'test-results/ledger-failure.png')}).catch(()=>{});console.error(e);throw e;}finally{await run.app.close().catch(()=>{});fs.unlinkSync(keyFile);}})().catch(()=>{process.exitCode=1;});
