// Development integration test: isolated test profile, no real user workspace or servers.
const { _electron: electron } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const profile = path.join(root, 'test-results', `profile-${Date.now()}`);
const executablePath = process.argv[2] || require('electron');
const args = process.argv[2] ? [] : [root];
const environment = { ...process.env, BANCYCRAFT_TEST_DATA: profile };
delete environment.ELECTRON_RUN_AS_NODE;
async function launch() {
  const application = await electron.launch({ executablePath, args, env: environment });
  const page = await application.firstWindow();
  await page.waitForFunction(() => document.body.textContent.includes('Your next build'));
  return { application, page };
}
(async () => {
  fs.mkdirSync(path.join(root, 'test-results'), { recursive: true });
  let run = await launch();
  try {
    const errors = [];
    run.page.on('pageerror', error => errors.push(error.message));
    const details = await run.page.evaluate(async () => ({ app: await window.bancy.info(), data: await window.bancy.load(), nodeVisible: typeof window.require !== 'undefined' }));
    assert.equal(details.app.version, require('../package.json').version);
    assert.equal(details.nodeVisible, false);
    assert.equal(details.data.plans.length, 0);
    const security = await run.application.evaluate(({ BrowserWindow }) => { const preferences = BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences(); return { sandbox: preferences.sandbox, contextIsolation: preferences.contextIsolation, nodeIntegration: preferences.nodeIntegration }; });
    assert.deepEqual(security, { sandbox: true, contextIsolation: true, nodeIntegration: false });
    assert.equal(await run.page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
    assert.equal(await run.page.locator('.game-card').count(), 6);
    assert.equal(await run.page.locator('.game-card.planned').count(), 1);
    await run.page.waitForFunction(() => [...document.querySelectorAll('.game-tile-image')].every(image => image.complete && image.naturalWidth > 0));
    assert.equal(await run.page.evaluate(() => [...document.querySelectorAll('.game-card.planned')].every(card => {
      const badge = card.querySelector('.planned-badge').getBoundingClientRect(), title = card.querySelector('.game-name').getBoundingClientRect();
      return title.top > badge.bottom;
    })), true, 'Planned badges must not overlap game titles');
    assert.equal(await run.page.getByRole('button', {name: 'Gathering Lists', exact: true}).count(), 0);
    assert.equal(await run.page.getByRole('button', {name: 'Shared Lists', exact: true}).count(), 0);
    await run.page.getByRole('button', {name: 'Shopping Lists', exact: true}).click();
    await run.page.getByRole('heading', {name: 'Private lists', exact: true}).waitFor();
    await run.page.getByRole('heading', {name: 'Shared lists', exact: true}).waitFor();
    assert.equal(await run.page.evaluate(() => {
      const privateHeading = document.querySelector('.private-lists-heading');
      const sharedHeading = document.querySelector('.shared-lists-heading');
      return !!document.querySelector('.list-sharing-divider') && !!(privateHeading.compareDocumentPosition(sharedHeading) & Node.DOCUMENT_POSITION_FOLLOWING);
    }), true);
    await run.page.screenshot({path: path.join(root, 'test-results', 'shopping-lists-combined.png')});
    await run.page.getByRole('button', {name: 'Home', exact: true}).click();
    await run.page.screenshot({ path: path.join(root, 'test-results', 'home-desktop.png') });
    // Catalogs must work offline and remain isolated by the active game.
    await run.page.context().setOffline(true);
    await run.page.getByRole('button', { name: 'Item Browser', exact: true }).click();
    await run.page.getByRole('heading', { name: 'Item browser', exact: true }).waitFor();
    await run.page.getByLabel('Search items', { exact: true }).fill('Coarse Thread');
    await run.page.getByRole('button', { name: 'View Coarse Thread', exact: true }).click();
    assert.match(await run.page.getByLabel('Item details', { exact: true }).innerText(), /Spinning Wheel/);
    assert.match(await run.page.getByLabel('Item details', { exact: true }).innerText(), /Coarse Animal Fur/);
    await run.page.getByRole('button', { name: 'Close Coarse Thread', exact: true }).click();
    await run.page.getByRole('button', { name: 'Show additional filters', exact: true }).click();
    await run.page.getByLabel('Search items', { exact: true }).fill('');
    await run.page.getByLabel('Crafting station', { exact: true }).selectOption('Loom');
    assert.ok(await run.page.locator('.search-result').count() > 0);
    await run.page.getByLabel('Crafting station', { exact: true }).selectOption('Tannery');
    assert.ok(await run.page.locator('.search-result').count() > 0);
    await run.page.getByRole('button', { name: 'Reset filters', exact: true }).click();
    await run.page.getByLabel('Search items', { exact: true }).fill('Coarse Thread');
    await run.page.getByLabel('Active game', { exact: true }).selectOption('valheim');
    await run.page.getByRole('heading', { name: 'No matching items' }).waitFor();
    await run.page.getByLabel('Search items', { exact: true }).fill('Bloodgold');
    await run.page.getByRole('button', { name: 'View Bloodgold', exact: true }).click();
    assert.match(await run.page.getByLabel('Item details', { exact: true }).innerText(), /Petrified Tissue/);
    await run.page.getByRole('button', { name: 'Close Bloodgold', exact: true }).click();
    await run.page.getByLabel('Active game', { exact: true }).selectOption('enshrouded');
    await run.page.getByRole('heading', { name: 'No matching items' }).waitFor();
    await run.page.getByLabel('Search items', { exact: true }).fill('Linen');
    await run.page.getByRole('button', { name: 'View Linen', exact: true }).click();
    assert.match(await run.page.getByLabel('Item details', { exact: true }).innerText(), /Spinning Machine/);
    await run.page.getByRole('button', { name: 'Close Linen', exact: true }).click();
    await run.page.getByLabel('Active game', { exact: true }).selectOption('grounded2');
    await run.page.getByLabel('Search items', { exact: true }).fill('Crude Rope');
    await run.page.getByRole('button', { name: 'View Crude Rope', exact: true }).click();
    assert.match(await run.page.getByLabel('Item details', { exact: true }).innerText(), /Spinning Wheel/);
    assert.match(await run.page.getByLabel('Item details', { exact: true }).innerText(), /Plant Fiber/);
    await run.page.getByRole('button', { name: 'Close Crude Rope', exact: true }).click();
    await run.page.screenshot({path:path.join(root,'test-results','grounded2-catalog.png')});
    await run.page.getByLabel('Active game', { exact: true }).selectOption('enshrouded');
    await run.page.getByLabel('Search items', { exact: true }).fill('Linen');
    assert.equal((await run.page.evaluate(() => window.bancy.load())).game, 'enshrouded');
    await run.page.screenshot({ path: path.join(root, 'test-results', 'catalog-desktop.png') });
    await run.application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1050, 740));
    assert.equal(await run.page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
    await run.page.screenshot({ path: path.join(root, 'test-results', 'catalog-compact.png') });
    const rejected = await run.page.evaluate(async () => { try { await window.bancy.openSource('file:///C:/Windows'); return false; } catch { return true; } });
    assert.equal(rejected, true);
    await run.page.reload();
    await run.page.getByRole('heading', { name: 'Your next build starts here.' }).waitFor();
    assert.equal(await run.page.getByLabel('Active game', { exact: true }).inputValue(), 'enshrouded');
    await run.page.getByLabel('Active game', { exact: true }).selectOption('dragonwilds');
    await run.page.waitForFunction(() => !document.querySelector('[aria-label="Active game"]').disabled);
    await run.application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1480, 980));
    // Exercise real renderer forms and Electron IPC, not the browser-preview fallback.
    await run.page.getByRole('button', { name: 'New crafting plan', exact: true }).click();
    await run.page.getByLabel('Plan name', { exact: true }).fill('Smoke test workshop');
    await run.page.getByLabel('Target quantity').fill('3');
    await run.page.getByLabel('Notes & material reminders').fill('Gather wood and iron.');
    await run.page.getByRole('button', { name: 'Save plan', exact: true }).click();
    await run.page.getByRole('dialog').waitFor({ state: 'hidden' });
    let stored = await run.page.evaluate(() => window.bancy.load());
    assert.equal(stored.plans[0].name, 'Smoke test workshop');
    assert.equal(stored.plans[0].quantity, 3);
    await run.page.getByRole('button', { name: 'My Supplies', exact: true }).click();
    await run.page.getByRole('button', { name: 'Add supply', exact: true }).click();
    await run.page.getByLabel('Material name').fill('Blightwood');
    await run.page.getByLabel('Quantity owned').fill('50');
    await run.page.getByRole('button', { name: 'Save supply', exact: true }).click();
    await run.page.getByRole('dialog').waitFor({ state: 'hidden' });
    assert.equal((await run.page.evaluate(() => window.bancy.load())).supplies[0]?.quantity, 50, 'Supply reaches the native store before leaving the page');
    await run.page.getByRole('button', { name: 'Settings & updates', exact: true }).click();
    await run.page.getByRole('heading', { name: 'BancyCraft updates' }).waitFor();
    await run.page.screenshot({ path: path.join(root, 'test-results', 'settings-desktop.png') });
    await run.page.getByLabel('BancyCraft cipher key',{exact:true}).waitFor();
    assert.equal(await run.page.getByRole('navigation',{name:'Connected features'}).count(),0,'Community sidebar is hidden without a validated key');
    await run.application.close();
    run = await launch();
    stored = await run.page.evaluate(() => window.bancy.load());
    assert.equal(stored.plans[0].name, 'Smoke test workshop');
    assert.equal(stored.supplies[0].quantity, 50);
    await run.page.getByRole('button', { name: 'Crafting Planner', exact: true }).click();
    await run.page.getByRole('button', { name: 'Edit Smoke test workshop' }).click();
    await run.page.getByRole('dialog').locator('select').nth(1).selectOption('completed');
    await run.page.getByRole('button', { name: 'Save plan', exact: true }).click();
    await run.page.getByRole('dialog').waitFor({ state: 'hidden' });
    assert.equal((await run.page.evaluate(() => window.bancy.load())).plans[0].status, 'completed');
    await run.page.getByRole('button', { name: 'Delete Smoke test workshop' }).click();
    await run.page.getByRole('button', { name: 'Delete', exact: true }).click();
    await run.page.getByRole('dialog').waitFor({ state: 'hidden' });
    assert.equal((await run.page.evaluate(() => window.bancy.load())).plans.length, 0);
    await run.application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1050, 740));
    await run.page.getByRole('button', { name: 'Home', exact: true }).click();
    assert.equal(await run.page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
    const helpBounds = await run.page.getByRole('button', { name: 'Help', exact: true }).boundingBox();
    assert.ok(helpBounds && helpBounds.y + helpBounds.height <= (await run.page.evaluate(() => window.innerHeight)), 'Help remains visible at the minimum window size');
    await run.page.screenshot({ path: path.join(root, 'test-results', 'home-compact.png') });
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ result: 'PASS', version: details.app.version, packaged: details.app.packaged, profile, checks: ['offline catalogs and game-scoped search', 'recipe alternatives and station filters', 'source link rejection', 'native startup', 'renderer isolation', 'plan create/edit/delete', 'supply save', 'persistence after restart', 'update settings', 'connection placeholder', 'desktop and compact layouts'] }, null, 2));
  } catch (error) {
    await run.page.screenshot({ path: path.join(root, 'test-results', 'failure.png') }).catch(() => {});
    console.error(await run.page.locator('body').innerText().catch(() => 'No renderer text'));
    throw error;
  } finally { await run.application.close().catch(() => {}); }
})().catch(error => { console.error(error); process.exitCode = 1; });
