const {_electron:electron}=require('@playwright/test'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),{randomUUID}=require('crypto');
const root=path.resolve(__dirname,'..'),profile=path.join(root,'test-results','tools-070-'+Date.now()),dev=process.argv.includes('--dev');
const c=require('../src/catalog/data/dragonwilds.json'),vis=c.items.find(i=>i.name==='Vis Cloth');const list={id:randomUUID(),name:'Vis workshop',game:'dragonwilds',targets:[{itemId:vis.id,name:vis.name,quantity:5}],quick:false,useSupplies:false,hideCompleted:false,recipes:{},progress:{},collapsed:{},updatedAt:new Date().toISOString()};
fs.mkdirSync(profile,{recursive:true});fs.writeFileSync(path.join(profile,'workspace.json'),JSON.stringify({schemaVersion:2,game:'valheim',plans:[],supplies:[],lists:[list]}));
const env={...process.env,BANCYCRAFT_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;
async function launch(){return electron.launch({executablePath:dev?require('electron'):path.join(root,'release/win-unpacked/BancyCraft.exe'),args:dev?[root]:[],env});}
(async()=>{let app=await launch();try{let page=await app.firstWindow();const failures=[];page.on('pageerror',e=>failures.push(e.message));await page.getByRole('button',{name:'Item Browser',exact:true}).click();await page.getByLabel('Search catalog',{exact:true}).fill('draugr f');assert.equal(await page.getByRole('button',{name:'View Draugr Fang',exact:true}).count(),1);await page.getByRole('button',{name:'Favorite Draugr Fang',exact:true}).click();await page.getByRole('button',{name:'Favorites',exact:true}).click();await page.getByRole('button',{name:'View Draugr Fang',exact:true}).click();await page.getByRole('button',{name:'Close Draugr Fang',exact:true}).click();await page.getByRole('button',{name:'Recently viewed',exact:true}).click();await page.getByRole('button',{name:'View Draugr Fang',exact:true}).waitFor();await page.screenshot({path:path.join(root,'test-results/browser-canonical.png')});
 await page.getByLabel('Active game',{exact:true}).selectOption('dragonwilds');await page.getByRole('button',{name:'Shopping Lists',exact:true}).click();assert.equal(await page.locator('.shopping-detail').count(),0);await page.getByRole('button',{name:/Vis workshop/}).click();await page.getByRole('heading',{name:'Vis workshop',exact:true}).waitFor();assert.equal(await page.locator('.saved-list-card').count(),0);const before=await page.evaluate(()=>window.bancy.load());
 const ingot=page.getByRole('article',{name:/Requirement Vis Cloth/});await page.getByLabel('Already owned Vis Cloth',{exact:true}).fill('2');await page.getByLabel('Already owned Vis Cloth',{exact:true}).press('Tab');await page.waitForFunction(()=>document.querySelector('[aria-label="Already owned Vis Cloth"]')?.value==='2');await page.getByRole('button',{name:'Undo last change',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="Already owned Vis Cloth"]')?.value==='0');assert.deepEqual((await page.evaluate(()=>window.bancy.load())).lists[0].owned,{});
 await page.getByLabel('Shopping list view',{exact:true}).selectOption('stations');assert(await page.getByRole('region',{name:'Loom section',exact:true}).count());await page.screenshot({path:path.join(root,'test-results/station-view.png')});await page.getByRole('button',{name:'Gaming checklist',exact:true}).click();assert(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()));await page.screenshot({path:path.join(root,'test-results/gaming-checklist.png')});await page.getByRole('button',{name:'Exit gaming checklist',exact:true}).click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()),false);
 await page.getByRole('button',{name:'Builds',exact:true}).click();await page.getByRole('button',{name:'New build',exact:true}).click();await page.getByLabel('Build name',{exact:true}).fill('Mithril boss build');await page.getByLabel('Build tags',{exact:true}).fill('Bossing, Exploration');await page.getByLabel('Build description',{exact:true}).fill('Equipment for the next boss.');await page.getByRole('button',{name:'Choose item for Main weapon',exact:true}).click();await page.getByLabel('Search build items',{exact:true}).fill('Mithril Mace');await page.locator('.build-picker-results').getByRole('button',{name:/Mithril Mace/}).click();await page.getByRole('button',{name:'Save build',exact:true}).click();await page.getByRole('button',{name:'Create variant',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="Build name"]')?.value.endsWith('(copy)'));await page.getByRole('button',{name:'Edit build',exact:true}).click();await page.getByLabel('Build name',{exact:true}).fill('Mithril exploration build');await page.getByRole('button',{name:'Save build',exact:true}).click();const tools=await page.evaluate(()=>window.bancy.toolsLoad());assert.equal(tools.builds.length,2);assert.equal(tools.builds[0].name,'Mithril boss build');assert.equal(tools.builds[1].name,'Mithril exploration build');assert.equal(tools.builds[0].items[0].name,'Mithril Mace');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(root,'test-results/build-editor.png')});await page.getByRole('button',{name:'Create full shopping list',exact:true}).click();await page.getByRole('dialog',{name:'Pick a list',exact:true}).waitFor();await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Production Ledger',exact:true}).click();const frame=page.frameLocator('iframe[title="Dragonwilds production tools"]');await frame.getByRole('heading',{name:'Production Ledger',exact:true}).waitFor();assert.equal(await frame.locator('.dw-tab:visible').count(),4);const bg=await frame.locator('body').evaluate(e=>getComputedStyle(e).backgroundColor);assert.equal(bg,'rgb(7, 17, 23)');await frame.locator('#profitInputAmount').count().then(()=>{});await page.screenshot({path:path.join(root,'test-results/ledger-profit-redesign.png')});await frame.getByRole('tab',{name:'Production Planner',exact:true}).click();await page.screenshot({path:path.join(root,'test-results/ledger-production-redesign.png')});await frame.getByRole('tab',{name:'Merchant Catalog',exact:true}).click();await page.screenshot({path:path.join(root,'test-results/ledger-merchant-redesign.png')});
 await page.getByRole('button',{name:'Settings & updates',exact:true}).click();await page.getByRole('button',{name:'Report a bug or suggest an idea',exact:true}).click();const feedback=page.frameLocator('iframe[title="BancyCraft feedback form"]');await feedback.getByRole('heading',{name:'BancyCraft · Reports & Suggestions',exact:true}).waitFor({timeout:30000});await feedback.getByRole('button',{name:'Submit',exact:true}).waitFor();assert.equal(await feedback.locator('body').evaluate(()=>typeof window.bancy),'undefined');assert.equal(await feedback.getByRole('textbox',{name:'Subject Required question',exact:true}).count(),1);await page.screenshot({path:path.join(root,'test-results/google-feedback-embed.png')});await page.keyboard.press('Escape');assert.deepEqual(failures,[]);
 await app.close();app=await launch();page=await app.firstWindow();await page.getByRole('button',{name:'Builds',exact:true}).click();await page.getByRole('button',{name:/^Mithril exploration build/}).waitFor();assert.equal((await page.evaluate(()=>window.bancy.toolsLoad())).builds.length,2);console.log('TOOLS_070_OK: canonical browser, favorites/recent, dedicated lists, owned deductions/undo, station view, native always-on-top checklist, independent build variants, list generation, redesigned ledger panels, public Google form isolation, restart persistence.');
 }catch(e){await (await app.firstWindow()).screenshot({path:path.join(root,'test-results/tools-070-failure.png')}).catch(()=>{});throw e;}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
