import React, { createContext, useContext, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Home, BookOpen, Hammer, Leaf, Box, LockKeyhole, Settings, CircleHelp, Search, Plus, ArrowRight, ArrowUpRight, Monitor, ScrollText, Database, Download, FolderOpen, Check, X, Trash2, Pencil, ChevronRight, Trees, Mountain, ShieldCheck, ExternalLink } from 'lucide-react';
import { api } from './bridge';
import type { Game, Info, Plan, Supply, Workspace } from './types';
import './styles.css';
import { ItemBrowser } from './catalog/Browser';

type Page = 'Home' | 'Item Browser' | 'Crafting Planner' | 'Gathering Lists' | 'My Supplies' | 'Shared Storage' | 'Group Plans' | 'Server Bank' | 'Settings' | 'Help';
const games: Record<Game, string> = { dragonwilds: 'RuneScape: Dragonwilds', valheim: 'Valheim', enshrouded: 'Enshrouded' };
const navigation = [{ label: 'Home', icon: Home }, { label: 'Item Browser', icon: BookOpen }, { label: 'Crafting Planner', icon: Hammer }, { label: 'Gathering Lists', icon: Leaf }, { label: 'My Supplies', icon: Box }] as const;
const shared = ['Shared Storage', 'Group Plans', 'Server Bank'] as const;
const empty: Workspace = { schemaVersion: 1, game: 'dragonwilds', plans: [], supplies: [] };
const SaveError = createContext('');
function App() {
  const [page, setPage] = useState<Page>('Home');
  const [data, setData] = useState<Workspace>(empty);
  const [info, setInfo] = useState<Info>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [loadFailed, setLoadFailed] = useState(false);
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState('');
  const [search, setSearch] = useState('');
  const [editing, setEditing] = useState<Plan | 'new' | null>(null);
  const [supplyEdit, setSupplyEdit] = useState<Supply | 'new' | null>(null);
  const [deleting, setDeleting] = useState<{ type: 'plan' | 'supply'; id: string; name: string } | null>(null);
  const [connection, setConnection] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);
  const dataRef = useRef(data);
  const saveLock = useRef(false);
  useEffect(() => {
    Promise.all([api.load(), api.info()]).then(([workspace, application]) => { dataRef.current = workspace; setData(workspace); setInfo(application); }).catch(err => { setLoadFailed(true); setError(String(err.message || err)); }).finally(() => setLoading(false));
    return api.onUpdate(update => setInfo(previous => previous ? { ...previous, update } : previous));
  }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); searchRef.current?.focus(); } }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, []);
  async function save(change: (current: Workspace) => Workspace) {
    if (saveLock.current || loadFailed) return false;
    saveLock.current = true; setBusy(true); setError('');
    try { const saved = await api.save(change(dataRef.current)); dataRef.current = saved; setData(saved); return true; }
    catch (err) { setError(err instanceof Error ? err.message : 'Your changes could not be saved.'); return false; }
    finally { saveLock.current = false; setBusy(false); }
  }
  function go(next: Page) { setPage(next); setSearch(''); }
  async function selectGame(game: Game, open = false) { if (await save(current => ({ ...current, game }))) { if (open) go('Item Browser'); } }
  const plans = data.plans.filter(plan => plan.game === data.game && `${plan.name} ${plan.notes}`.toLowerCase().includes(search.toLowerCase()));
  const supplies = data.supplies.filter(item => item.game === data.game && item.name.toLowerCase().includes(search.toLowerCase()));
  const canWrite = !busy && !loading && !loadFailed;
  const connectButton = <button className="button outline full" onClick={() => setConnection(true)}>Connect to Bancy.gg <ArrowUpRight size={17}/></button>;
  const newPlan = () => setEditing('new');

  if (loading) return <div className="boot"><span className="brand-letter">B</span><h1>BancyCraft</h1><p>Opening your workspace…</p></div>;
  return <SaveError.Provider value={error}><div className="app-shell">
    <aside className="sidebar">
      <button className="brand" onClick={() => go('Home')} aria-label="BancyCraft home"><img className="brand-wordmark" src="./assets/bancycraft-wordmark.png" alt="BancyCraft"/><span className="eyebrow">Plan · Craft · Progress</span></button>
      <nav aria-label="Main navigation">{navigation.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${page === label ? 'active' : ''}`} onClick={() => go(label)} aria-current={page === label ? 'page' : undefined}><Icon size={20}/><span>{label}</span></button>)}</nav>
      <div className="nav-divider"><span>Bancy.gg</span><span className="tiny-badge">Optional</span></div>
      <nav aria-label="Connected features">{shared.map(label => <button key={label} className={`nav-item shared ${page === label ? 'active' : ''}`} onClick={() => go(label)}><LockKeyhole size={17}/><span>{label}</span></button>)}</nav>
      <div className="sidebar-bottom"><button className={`nav-item ${page === 'Settings' ? 'active' : ''}`} onClick={() => go('Settings')}><Settings size={19}/>Settings & updates</button><button className={`nav-item ${page === 'Help' ? 'active' : ''}`} onClick={() => go('Help')}><CircleHelp size={19}/>Help</button><div className="sidebar-motto">Good games.<br/>Better builds.</div></div>
    </aside>
    <div className="main-shell">
      <header className="toolbar"><div className="breadcrumb"><Home size={17}/><span>/</span>{page}</div><label className="toolbar-game">Game<select aria-label="Active game" disabled={!canWrite} value={data.game} onChange={event => selectGame(event.target.value as Game)}>{Object.entries(games).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label><label className="search"><Search size={17}/><input ref={searchRef} aria-label="Search items" placeholder={`Search ${games[data.game]} items…`} value={search} onChange={event => { setSearch(event.target.value); setPage('Item Browser'); }}/><kbd>Ctrl K</kbd></label><span className="local-status"><i/>Local mode</span></header>
      <main>
        {error && <div className="error-banner" role="alert"><div><strong>{loadFailed ? 'Your workspace needs attention' : 'Unable to complete that action'}</strong><p>{error}</p>{loadFailed && <button className="text-button" onClick={() => api.openData()}>Open data folder</button>}</div>{!loadFailed && <button aria-label="Dismiss error" onClick={() => setError('')}><X size={18}/></button>}</div>}
        <>
        {page === 'Home' && <>
          <section className="hero panel"><div className="hero-content"><p className="eyebrow">Crafting builds stronger stories</p><h1>Your next build<br/>starts here.</h1><p className="hero-description">Plan your crafts. Know your materials.</p><div className="actions"><button className="button primary" disabled={!canWrite} onClick={newPlan}><Plus size={19}/>New crafting plan</button><button className="button outline" onClick={() => go('Item Browser')}>Browse items <ArrowRight size={16}/></button></div></div><div className="hero-caption">Same materials.<br/>Brighter adventures.</div></section>
          <div className="home-grid"><section className="panel games-panel"><SectionTitle number="01" title="Choose your game" aside="Different worlds. More to craft."/><div className="game-grid">{(['dragonwilds', 'valheim', 'enshrouded'] as const).map(game => <button className={`game-card ${game}`} key={game} disabled={!canWrite} onClick={() => selectGame(game, true)}><div className="game-art"><span className="game-symbol">{game === 'dragonwilds' ? <Trees size={38}/> : <Mountain size={38}/>}</span>{game === 'dragonwilds' && <span className="game-prefix">RuneScape</span>}<span className="game-name">{game === 'dragonwilds' ? 'Dragonwilds' : games[game]}</span></div><div className="game-card-footer"><Monitor size={15}/><span>Local planning</span><strong>Browse items <ArrowRight size={15}/></strong></div></button>)}</div></section>
          <section className="panel connect-panel"><h2>Craft together.</h2><p>Connect for shared storage, group plans and server resources.</p>{connectButton}<small>Browser sign-in integration is coming next.</small><div className="connection-note">Your local tools work without an account.</div></section>
          <section className="panel workspace-panel"><SectionTitle number="02" title="Your workspace" aside={`${data.plans.length} saved ${data.plans.length === 1 ? 'plan' : 'plans'}`}/>{data.plans.length ? <div className="recent-plans">{[...data.plans].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 3).map(plan => <button key={plan.id} className="recent-plan" onClick={() => setEditing(plan)}><ScrollText size={23}/><span><strong>{plan.name}</strong><small>{games[plan.game]} · Quantity {plan.quantity}</small></span><span className={`status ${plan.status}`}>{plan.status.replace('-', ' ')}</span><ChevronRight size={18}/></button>)}<button className="text-button" onClick={() => go('Crafting Planner')}>View all plans <ArrowRight size={15}/></button></div> : <div className="empty-state home-empty"><ScrollText size={43} strokeWidth={1}/><h2>Start your first crafting plan</h2><p>Give your next project a name. Build out the details as you go.</p><button className="text-button" disabled={!canWrite} onClick={newPlan}>Create a plan <ArrowRight size={16}/></button></div>}</section>
          <section className="panel how-panel"><SectionTitle number="03" title="Start here"/>{[{ icon: ScrollText, title: 'Make a plan', description: 'Name your project and choose a game.' }, { icon: Box, title: 'Note your supplies', description: 'Keep a local record of what you own.' }, { icon: Download, title: 'Grow your workspace', description: 'Keep your plans as new features arrive.' }].map(({ icon: Icon, title, description }, index) => <div className="how-step" key={title}><span className="step-number">0{index + 1}</span><Icon size={25} strokeWidth={1.3}/><div><strong>{title}</strong><p>{description}</p></div></div>)}</section></div>
        </>}
        {page === 'Crafting Planner' && <><PageHeading eyebrow="PLAN · CRAFT · PROGRESS" title="Crafting planner" description="Your next builds, saved on this computer." action={<button className="button primary" disabled={!canWrite} onClick={newPlan}><Plus size={17}/>New plan</button>}/><GameSelect value={data.game} disabled={!canWrite} onChange={selectGame}/><div className="notice"><Hammer size={18}/><p>This first build supports manual plans and notes. Recipe calculations and material reservations are coming later.</p></div><section className="panel content-panel"><PlanList plans={plans} onEdit={setEditing} onDelete={plan => setDeleting({ type: 'plan', ...plan })}/>{!plans.length && <button className="button outline" disabled={!canWrite} onClick={newPlan}><Plus size={17}/>Create your first plan</button>}</section></>}
        {page === 'My Supplies' && <><PageHeading eyebrow="YOUR LOCAL INVENTORY" title="My supplies" description="Manually record the materials you have. Only stored on this computer." action={<button className="button primary" disabled={!canWrite} onClick={() => setSupplyEdit('new')}><Plus size={17}/>Add supply</button>}/><GameSelect value={data.game} disabled={!canWrite} onChange={selectGame}/><section className="panel content-panel">{supplies.length ? <><div className="table-heading"><span>Material</span><span>Quantity</span></div>{supplies.map(item => <div className="supply-row" key={item.id}><Box size={19}/><span>{item.name}</span><strong>{item.quantity.toLocaleString()}</strong><button className="icon-button" aria-label={`Edit ${item.name}`} disabled={!canWrite} onClick={() => setSupplyEdit(item)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${item.name}`} disabled={!canWrite} onClick={() => setDeleting({ type: 'supply', ...item })}><Trash2 size={16}/></button></div>)}</> : <div className="empty-state"><Box size={43} strokeWidth={1}/><h2>A place for your materials</h2><p>Add your first supply to start a local inventory.</p><button className="text-button" disabled={!canWrite} onClick={() => setSupplyEdit('new')}>Add a supply <Plus size={16}/></button></div>}</section></>}
        {page === 'Item Browser' && <ItemBrowser key={data.game} game={data.game} query={search} onQuery={setSearch}/>}
        {page === 'Gathering Lists' && <><PageHeading eyebrow="EVERY ADVENTURE HAS A LIST" title="Gathering lists" description="See the materials your crafting plans still need."/><ComingSoon icon={<Leaf size={48} strokeWidth={1}/>} title="Know what to bring home" description="Automatic gathering lists will arrive with the recipe engine. For now, you can keep material reminders in your plan notes."/><button className="button outline" onClick={() => go('Crafting Planner')}>Open your plans <ArrowRight size={16}/></button></>}
        {shared.includes(page as typeof shared[number]) && <><PageHeading eyebrow="BANCY.GG · CONNECTED FEATURES" title={page} description="A shared workspace for your Bancy community."/><section className="panel connected-placeholder"><LockKeyhole size={44} strokeWidth={1}/><h2>Your worlds, connected.</h2><p>{page === 'Shared Storage' ? 'Find materials across your community’s server chests.' : page === 'Group Plans' ? 'Coordinate builds, material reservations and contributions together.' : 'View approved bank totals and reconciliation information.'}</p><div className="connection-button">{connectButton}</div><span className="coming-tag">Coming in a future build</span><p className="muted">BancyCraft does not connect to Blackbox or read game saves in this version.</p></section></>}
        {page === 'Settings' && <><PageHeading eyebrow="MAKE YOURSELF AT HOME" title="Settings & updates" description="Your installation, your workspace, your next version."/><div className="settings-grid"><section className="panel content-panel"><h2><Download size={22}/>BancyCraft updates</h2><div className="version-row"><strong>Version {info?.version ?? __APP_VERSION__}</strong><span className="coming-tag">Catalog release</span></div><p>{info?.update.message}</p>{['manual', undefined].includes(info?.update.state) ? <ol className="update-steps"><li>Download the newer BancyCraft installer.</li><li>Close BancyCraft and run the installer.</li><li>Open BancyCraft. Your plans and settings remain.</li></ol> : <div className="actions">{['idle', 'current', 'error'].includes(info?.update.state ?? '') && <button className="button outline" onClick={async () => { const update = await api.checkUpdate(); setInfo(previous => previous ? { ...previous, update } : previous); }}>Check for updates</button>}{info?.update.state === 'available' && <button className="button primary" onClick={() => api.downloadUpdate()}>Download update</button>}{info?.update.state === 'ready' && <button className="button primary" onClick={() => api.installUpdate()}>Restart & install</button>}</div>}<div className="notice compact">Automatic update downloads will become available when the release feed is connected.</div></section><section className="panel content-panel"><h2><Database size={22}/>Local workspace</h2><p>Plans, supplies and your game selection are saved outside the app’s installation folder.</p><code className="data-path">{info?.dataPath}</code><div className="actions"><button className="button outline" disabled={!window.bancy} onClick={() => api.openData()}><FolderOpen size={17}/>Open folder</button><button className="button outline" disabled={!canWrite || !window.bancy} onClick={async () => { try { if (await api.exportWorkspace()) setToast('Workspace backup saved.'); } catch { setError('The workspace backup could not be saved.'); } }}><Download size={17}/>Back up</button></div><p className="muted">A previous-save backup is kept automatically. Nothing is uploaded.</p></section><section className="panel content-panel"><h2><Monitor size={22}/>Default game</h2><p>Choose which local workspace opens in the planner.</p><GameSelect value={data.game} disabled={!canWrite} onChange={selectGame}/></section><section className="panel content-panel"><h2><ShieldCheck size={22}/>Bancy connection</h2><p>Local mode · Not connected</p><p className="muted">Website sign-in, permissions and Blackbox access will be added together in a later version.</p>{connectButton}</section></div></>}
        {page === 'Help' && <><PageHeading eyebrow="A GOOD PLACE TO START" title="Welcome to BancyCraft" description="An independent crafting workspace, with optional Bancy community features."/><div className="panel content-panel help-content"><h2>What works in this version?</h2><p>Create, edit and delete local crafting plans. Track their status, add your supplies, browse offline item catalogs for Dragonwilds, Valheim and Enshrouded, and back up your data. Your work remains after restarting or updating the app.</p><h2>What is coming next?</h2><p>Complete recipe coverage, quantity calculators, gathering lists, secure Bancy.gg sign-in and optional shared Blackbox inventory. These screens are intentionally labeled until their integrations are ready.</p><h2>How do I update?</h2><p>Run the next BancyCraft installer over this installation. Keep the same install location. You do not need to uninstall first. Your workspace lives in a separate BancyCraft data folder.</p><h2>Do I need an account?</h2><p>No. Local planning works without a website account or Blackbox. Connecting will be optional and will only enable the community features your account can access.</p><button className="text-button" onClick={() => api.openWebsite()}>Visit Bancy.gg <ExternalLink size={16}/></button></div></>}
        </>
        <footer><span><Database size={14}/>{busy ? 'Saving…' : loadFailed ? 'Workspace unavailable' : 'Workspace saved on this computer'}</span><span>BancyCraft {info?.version ?? __APP_VERSION__} <i/> Local workspace</span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {editing && <PlanDialog plan={editing === 'new' ? undefined : editing} game={data.game} busy={!canWrite} onClose={() => setEditing(null)} onSave={async plan => { if (await save(current => ({ ...current, plans: current.plans.some(item => item.id === plan.id) ? current.plans.map(item => item.id === plan.id ? plan : item) : [...current.plans, plan] }))) { setEditing(null); setToast('Plan saved on this computer.'); } }}/>}
    {supplyEdit && <SupplyDialog supply={supplyEdit === 'new' ? undefined : supplyEdit} game={data.game} busy={!canWrite} onClose={() => setSupplyEdit(null)} onSave={async item => { if (await save(current => ({ ...current, supplies: current.supplies.some(row => row.id === item.id) ? current.supplies.map(row => row.id === item.id ? item : row) : [...current.supplies, item] }))) { setSupplyEdit(null); setToast('Supply saved.'); } }}/>}
    {deleting && <Modal title={`Delete ${deleting.type}?`} onClose={() => setDeleting(null)}><p>Remove “{deleting.name}” from your local workspace?</p><div className="modal-actions"><button className="button outline" onClick={() => setDeleting(null)}>Keep it</button><button className="button danger" disabled={!canWrite} onClick={async () => { if (await save(current => ({ ...current, plans: deleting.type === 'plan' ? current.plans.filter(plan => plan.id !== deleting.id) : current.plans, supplies: deleting.type === 'supply' ? current.supplies.filter(item => item.id !== deleting.id) : current.supplies }))) { setDeleting(null); setToast('Removed from your workspace.'); } }}>Delete</button></div></Modal>}
    {connection && <Modal title="Connect to Bancy.gg" onClose={() => setConnection(false)}><div className="modal-emblem"><LockKeyhole size={34}/></div><p>Secure app sign-in is coming in a future update. You can visit Bancy.gg now, but signing in there will not connect this build or unlock Blackbox data yet.</p><div className="notice compact">Your local crafting plans and supplies work without connecting.</div><div className="modal-actions"><button className="button outline" onClick={() => setConnection(false)}>Keep planning</button><button className="button primary" onClick={() => api.openWebsite()}>Open Bancy.gg <ArrowUpRight size={17}/></button></div></Modal>}
  </div></SaveError.Provider>;
}
function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function SectionTitle({ number, title, aside }: { number: string; title: string; aside?: string }) { return <div className="section-title"><span><em>// {number}</em>{title}</span>{aside && <small>{aside}</small>}</div>; }
function GameSelect({ value, onChange, disabled }: { value: Game; onChange: (game: Game) => void; disabled: boolean }) { return <label className="game-select">Game<select value={value} disabled={disabled} onChange={event => onChange(event.target.value as Game)}>{Object.entries(games).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>; }
function PlanList({ plans, onEdit, onDelete }: { plans: Plan[]; onEdit: (plan: Plan) => void; onDelete: (plan: Plan) => void }) { return plans.length ? <div className="plan-list">{[...plans].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).map(plan => <article className="plan-row" key={plan.id}><ScrollText size={27}/><div className="plan-summary"><h3>{plan.name}</h3><p>Quantity {plan.quantity.toLocaleString()} · {games[plan.game]}</p>{plan.notes && <p className="plan-notes">{plan.notes}</p>}</div><span className={`status ${plan.status}`}>{plan.status.replace('-', ' ')}</span><button className="icon-button" aria-label={`Edit ${plan.name}`} onClick={() => onEdit(plan)}><Pencil size={17}/></button><button className="icon-button" aria-label={`Delete ${plan.name}`} onClick={() => onDelete(plan)}><Trash2 size={17}/></button></article>)}</div> : <div className="empty-state"><ScrollText size={39} strokeWidth={1}/><h2>No plans here yet</h2><p>Your next project starts with a name.</p></div>; }
function ComingSoon({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <section className="panel coming-soon"><span className="coming-tag">Coming next</span>{icon}<h2>{title}</h2><p>{description}</p></section>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  const saveError = useContext(SaveError);
  useEffect(() => { const dialog = ref.current!; const previous = document.activeElement as HTMLElement | null; dialog.showModal(); return () => { dialog.close(); previous?.focus(); }; }, []);
  return <dialog ref={ref} className="modal" aria-labelledby="modal-title" onCancel={event => { event.preventDefault(); onClose(); }}><div className="modal-header"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={21}/></button></div>{saveError && <div className="error-banner" role="alert">{saveError}</div>}{children}</dialog>;
}
function PlanDialog({ plan, game, busy, onClose, onSave }: { plan?: Plan; game: Game; busy: boolean; onClose: () => void; onSave: (plan: Plan) => void }) {
  const [name, setName] = useState(plan?.name ?? ''); const [selected, setSelected] = useState(plan?.game ?? game); const [quantity, setQuantity] = useState(String(plan?.quantity ?? 1)); const [notes, setNotes] = useState(plan?.notes ?? ''); const [status, setStatus] = useState<Plan['status']>(plan?.status ?? 'planned');
  return <Modal title={plan ? 'Edit crafting plan' : 'New crafting plan'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); if (name.trim()) onSave({ id: plan?.id ?? crypto.randomUUID(), name: name.trim(), game: selected, quantity: Number(quantity), notes, status, updatedAt: new Date().toISOString() }); }}><label>Plan name<input autoFocus required maxLength={120} value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Upgrade the workshop"/></label><div className="form-row"><label>Game<select value={selected} onChange={event => setSelected(event.target.value as Game)}>{Object.entries(games).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Target quantity<input type="number" min="1" max="999999" step="1" required value={quantity} onChange={event => setQuantity(event.target.value)}/></label></div><label>Status<select value={status} onChange={event => setStatus(event.target.value as Plan['status'])}><option value="planned">Planned</option><option value="in-progress">In progress</option><option value="completed">Completed</option></select></label><label>Notes & material reminders<textarea rows={4} maxLength={5000} value={notes} onChange={event => setNotes(event.target.value)} placeholder="Materials to gather, stations to build, ideas to remember…"/></label><p className="muted small">Manual plan · Recipe calculations will arrive in a later update.</p><div className="modal-actions"><button type="button" className="button outline" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || !name.trim()} type="submit"><Check size={16}/>{busy ? 'Saving…' : 'Save plan'}</button></div></form></Modal>;
}
function SupplyDialog({ supply, game, busy, onClose, onSave }: { supply?: Supply; game: Game; busy: boolean; onClose: () => void; onSave: (supply: Supply) => void }) {
  const [name, setName] = useState(supply?.name ?? ''); const [selected, setSelected] = useState(supply?.game ?? game); const [quantity, setQuantity] = useState(String(supply?.quantity ?? 0));
  return <Modal title={supply ? 'Edit supply' : 'Add supply'} onClose={onClose}><form onSubmit={event => { event.preventDefault(); if (name.trim()) onSave({ id: supply?.id ?? crypto.randomUUID(), name: name.trim(), game: selected, quantity: Number(quantity) }); }}><label>Material name<input autoFocus required maxLength={120} value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Wood"/></label><div className="form-row"><label>Game<select value={selected} onChange={event => setSelected(event.target.value as Game)}>{Object.entries(games).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Quantity owned<input type="number" min="0" max="999999" step="1" required value={quantity} onChange={event => setQuantity(event.target.value)}/></label></div><div className="modal-actions"><button type="button" className="button outline" onClick={onClose}>Cancel</button><button type="submit" className="button primary" disabled={busy || !name.trim()}><Check size={16}/>Save supply</button></div></form></Modal>;
}
createRoot(document.getElementById('root')!).render(<App/>);
