import {useEffect,useState} from 'react';
import {Plus,Shield,Copy,ShoppingCart,Share2,Download,Upload,Trash2} from 'lucide-react';
import type {Build,Game,Account} from '../types';
import type {AddRequest} from '../planner/ListPicker';
import {catalogs,gameNames} from '../catalog/catalogs';
import {canonicalItems,broadType,indexCatalog,itemKey} from '../planner/engine.mjs';
import {ItemIcon} from '../catalog/ItemIcon';
import {api} from '../bridge';
import {useTools} from './useTools';
import './tools.css';
const slots:Record<Game,string[]>={valheim:['Head','Chest','Legs','Cape','Main weapon','Off-hand','Utility','Food 1','Food 2','Food 3'],dragonwilds:['Head','Body','Legs','Main weapon','Off-hand','Food 1','Food 2','Potion'],enshrouded:['Head','Chest','Gloves','Legs','Boots','Main weapon','Ranged weapon','Ring 1','Ring 2','Food 1','Food 2','Food 3'],grounded2:['Head','Upper body','Lower body','Main weapon','Off-hand','Trinket','Consumable'],vrising:['Head','Chest','Gloves','Legs','Boots','Main weapon','Jewelry','Consumable']};
function Person({member}:{member?:Build['owner']}){const [image,setImage]=useState(''),[name,setName]=useState(member?.displayName||'You');useEffect(()=>{setImage('');setName(member?.displayName||'You');if(member)api.profileAvatar(member.uid).then(p=>{if(p){setImage(p.image);setName(p.displayName);}}).catch(()=>{});},[member?.uid]);return <span className="build-person">{image?<img src={image} alt=""/>:<span className="avatar-fallback">{name.slice(0,2).toUpperCase()}</span>}{name}</span>;}
export function Builds({game,account,onList}:{game:Game;account:Account;onList:(r:AddRequest)=>void}){
 const tools=useTools(),[selected,setSelected]=useState<Build>(),[remote,setRemote]=useState<Build[]>([]),[tab,setTab]=useState<'mine'|'community'>('mine'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pick,setPick]=useState<string>(),[search,setSearch]=useState(''),[updated,setUpdated]=useState<Build>(),[deleting,setDeleting]=useState(false);
 useEffect(()=>{setSelected(undefined);setQuery('');setPage(0);setUpdated(undefined);},[game]);
 const mine=selected&&tools.data.builds.some(b=>b.id===selected.id),catalog=catalogs[game],index=indexCatalog(catalog);
 async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Unable to complete this action.');}finally{setBusy(false);}}
 async function persist(b:Build){if(await tools.save(v=>({...v,builds:v.builds.some(x=>x.id===b.id)?v.builds.map(x=>x.id===b.id?b:x):[...v.builds,b]})))setSelected(b);else throw Error('Build could not be saved.');}
 function fresh(base?:Build):Build{return {id:crypto.randomUUID(),game,name:base?base.name+' (copy)':'New build',tags:base?.tags||[],description:base?.description||'',skills:base?.skills||'',items:base?.items.map(i=>({...i}))||[],updatedAt:new Date().toISOString(),...((base?.owner||base?.creator)?{creator:base.creator||base.owner,sourceId:base.sourceId||base.id,sourceUpdatedAt:base.sourceUpdatedAt||base.updatedAt}:{})};}
 function shopping(b:Build){const targets=new Map<string,AddRequest['targets'][number]>();for(const i of b.items){const t=targets.get(i.itemId);targets.set(i.itemId,{itemId:i.itemId,name:i.name,quantity:(t?.quantity||0)+i.quantity});}onList({game,targets:[...targets.values()]});}
 const results=(tab==='mine'?tools.data.builds:remote).filter(b=>b.game===game&&`${b.name} ${b.tags.join(' ')} ${b.description} ${b.owner?.displayName||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const current=Math.min(page,Math.max(0,Math.ceil(results.length/12)-1));
 return <section className="builds"><div className="page-heading"><div><p className="eyebrow">EQUIP · SAVE · SHARE</p><h1>{selected?selected.name:'Builds'}</h1><p>{gameNames[game]} · Equipment and ideas for your next adventure.</p></div>{!selected&&<button className="button primary" disabled={tools.busy||busy} onClick={()=>act(()=>persist(fresh()))}><Plus size={18}/>New build</button>}</div>{(error||tools.error)&&<p className="notice" role="alert">{error||tools.error}</p>}{notice&&<p role="status">{notice}</p>}
 {!selected?<><div className="actions build-tabs"><button className={'button '+(tab==='mine'?'primary':'outline')} onClick={()=>{setTab('mine');setPage(0);}}>My builds</button><button className={'button '+(tab==='community'?'primary':'outline')} onClick={()=>{setTab('community');setPage(0);if(account.state==='connected')void act(async()=>setRemote(await api.buildsBrowse(game)));}}>Community builds</button><button className="button outline" disabled={busy||tools.busy||!window.bancy} onClick={()=>act(async()=>{const b=await api.importBuild();if(b){if(b.game!==game)throw Error('Select '+gameNames[b.game]+' to import this build.');await persist(b);}})}><Upload size={16}/>Import build</button></div>{tab==='community'&&account.state!=='connected'?<section className="panel content-panel"><h2>Build with your community</h2><p>Connect your website account in Settings to browse and share builds. My builds work offline.</p></section>:<><label className="catalog-search"><Shield size={18}/><input placeholder="Find a build, tag or creator…" aria-label="Find builds" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>{tab==='community'&&<div className="actions"><button className="text-button" disabled={busy} onClick={()=>act(async()=>setRemote(await api.buildsBrowse(game)))}>Refresh community builds</button><small>Showing up to 200 builds for this game.</small></div>}<div className="build-card-grid">{results.slice(current*12,current*12+12).map(b=><button className="panel build-card" key={b.id} onClick={()=>{setSelected(structuredClone(b));setUpdated(undefined);setDeleting(false);}}><div className="build-card-icons">{b.items.slice(0,4).map((i,n)=><ItemIcon game={game} id={i.itemId} key={n}/>)}</div><h2>{b.name}</h2><p>{b.tags.join(' · ')||'No tags yet'}</p><small>{b.items.length} slots · {tab==='mine'?'Private copy':'Shared'}</small>{b.owner&&<Person member={b.owner}/>}</button>)}</div>{!results.length&&<section className="panel empty-state"><Shield size={40}/><h2>{tab==='mine'?'Your adventures, equipped':'No shared builds found'}</h2><p>{tab==='mine'?'Create a build or save a community build as your own private copy.':'Refresh or try another search.'}</p></section>}<div className="numbered-pagination"><button className="button outline" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {Math.max(1,Math.ceil(results.length/12))}</span><button className="button outline" disabled={(current+1)*12>=results.length} onClick={()=>setPage(current+1)}>Next</button></div></>}</>:<>
 <button className="text-button" onClick={()=>{setSelected(undefined);setUpdated(undefined);setDeleting(false);}}>← All builds</button><section className="panel build-editor"><div className="build-attribution"><span>{mine?'Private · saved on this computer':'Community build'}</span>{selected.owner&&<><span>Shared by</span><Person member={selected.owner}/></>}{selected.creator&&<><span>Original creator</span><Person member={selected.creator}/></>}</div>
 <label>Build name<input aria-label="Build name" maxLength={140} readOnly={!mine||busy||tools.busy} value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Tags<input aria-label="Build tags" maxLength={400} readOnly={!mine||busy||tools.busy} value={selected.tags.join(', ')} onChange={e=>setSelected({...selected,tags:e.target.value.split(',').slice(0,12).map(t=>t.trim().slice(0,40))})} placeholder="Bossing, Exploration, Gathering, Survival…"/></label><label>Description<textarea aria-label="Build description" maxLength={6000} readOnly={!mine||busy||tools.busy} rows={3} value={selected.description} onChange={e=>setSelected({...selected,description:e.target.value})}/></label>
 <div className="build-slot-grid">{[...new Set([...slots[game],...selected.items.map(i=>i.slot)])].map(slot=>{const item=selected.items.find(i=>i.slot===slot);return <div className="build-slot" key={slot}><small>{slot}</small>{item?<><ItemIcon game={game} id={item.itemId}/><strong>{item.name}</strong><label>Quantity<input aria-label={'Quantity in '+slot} disabled={!mine||busy||tools.busy} type="number" min={1} max={999999} value={item.quantity} onChange={e=>{const n=Number(e.target.value);if(Number.isSafeInteger(n)&&n>0&&n<=999999)setSelected({...selected,items:selected.items.map(i=>i.slot===slot?{...i,quantity:n}:i)});}}/></label></>:<span className="muted">Empty slot</span>}{mine&&<div className="actions"><button className="text-button" onClick={()=>{setPick(slot);setSearch('');}}>Choose item</button>{item&&<button className="text-button" onClick={()=>setSelected({...selected,items:selected.items.filter(i=>i.slot!==slot)})}>Remove</button>}</div>}</div>;})}</div>
 <label>Skills, mutations, spells & play notes<textarea aria-label="Build skills and notes" maxLength={6000} readOnly={!mine||busy||tools.busy} rows={4} value={selected.skills} onChange={e=>setSelected({...selected,skills:e.target.value})} placeholder="Record the choices that apply to this game. No unsupported stat calculations."/></label>
 <div className="actions">{mine&&<button className="button primary" disabled={busy||tools.busy||!selected.name.trim()} onClick={()=>act(async()=>{await persist({...selected,updatedAt:new Date().toISOString()});setNotice('Build saved privately.');})}>Save build</button>}<button className="button outline" disabled={busy||tools.busy} onClick={()=>act(async()=>{await persist(fresh(selected));setNotice('Independent private copy saved to My Builds.');})}><Copy size={16}/>{mine?'Create variant':'Save Build to My Builds'}</button><button className="button primary" disabled={!selected.items.length} onClick={()=>shopping(selected)}><ShoppingCart size={16}/>Create full shopping list</button><button className="button outline" disabled={busy||!window.bancy} onClick={()=>act(async()=>{if(await api.exportBuild(selected))setNotice('Build exported.');})}><Download size={16}/>Export</button>
 {mine&&<button className="button outline" disabled={busy||tools.busy||account.state!=='connected'||!selected.name.trim()} onClick={()=>act(async()=>{const b=await api.buildsPublish(selected);await persist(b);setRemote(r=>[...r.filter(x=>x.id!==b.id),b]);setNotice('Shared with signed-in BancyCraft members. Your local copy remains editable.');})}><Share2 size={16}/>{selected.publishedAt?'Update shared build':'Share build'}</button>}
 {mine&&selected.publishedAt&&<button className="text-button" disabled={busy} onClick={()=>act(async()=>{await api.buildsRemove(selected.id);const b={...selected};delete b.publishedAt;delete b.owner;await persist(b);setNotice('Unshared. Your private copy remains.');})}>Unshare</button>}
 {mine&&selected.sourceId&&<button className="text-button" disabled={busy||account.state!=='connected'} onClick={()=>act(async()=>{const b=await api.buildsGet(selected.sourceId!);if(b&&b.updatedAt!==selected.sourceUpdatedAt)setUpdated(b);else setNotice(b?'Your saved source is current.':'The original is no longer shared. Your copy is safe.');})}>Check original for updates</button>}
 {mine&&<button className="text-button" onClick={()=>setDeleting(true)}><Trash2 size={16}/>Delete private copy</button>}</div>
 {updated&&<section className="notice build-update"><h3>Updated since you saved it</h3><p>{updated.name} · {updated.tags.join(' · ')}</p><p>{updated.description}</p><ul>{updated.items.map((i,n)=><li key={n}>{i.slot}: {i.quantity} × {i.name}</li>)}</ul><p>{updated.skills}</p><button className="button outline" disabled={busy} onClick={()=>act(async()=>{await persist({...fresh(updated),name:updated.name+' (updated copy)'});setUpdated(undefined);setNotice('Updated version saved as a separate private copy. Your existing variant is unchanged.');})}>Save updated version as new copy</button></section>}
 {deleting&&<div className="notice"><p>Delete this private build? Shared versions remain until you unshare them.</p><button className="button danger" disabled={busy} onClick={()=>act(async()=>{if(await tools.save(v=>({...v,builds:v.builds.filter(b=>b.id!==selected.id)}))){setSelected(undefined);setDeleting(false);}})}>Delete copy</button><button className="text-button" onClick={()=>setDeleting(false)}>Keep it</button></div>}
 {pick&&<section className="build-picker" aria-label="Choose build item"><div className="actions"><h3>{pick}</h3><button className="text-button" onClick={()=>setPick(undefined)}>Close picker</button></div><input autoFocus aria-label="Search build items" placeholder="Search equipment or consumables…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="build-picker-results">{canonicalItems(catalog).filter(i=>(['Weapons','Armor','Consumables'].includes(broadType(i,index.recipes.has(itemKey(i))))||/jewel|accessor|ring|trinket|utility/i.test(i.category))&&i.name.toLowerCase().includes(search.toLowerCase())).slice(0,40).map(i=><button key={i.id} onClick={()=>{setSelected({...selected,items:[...selected.items.filter(i=>i.slot!==pick),{slot:pick,itemId:i.id,name:i.name,quantity:1}]});setPick(undefined);}}><ItemIcon game={game} id={i.id}/><span>{i.name}<small>{i.category}</small></span></button>)}</div><p className="muted small">Search shows up to 40 results. Slot choices are flexible; check the game’s equipment restrictions.</p></section>}</section></>}
 </section>;
}
