import {useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Ban,Copy,Minus,Pencil,Plus,Trash2} from 'lucide-react';
import type {Build,BuildImage,BuildItem,BuildVariant,Game} from '../types';
import {catalogs} from '../catalog/catalogs';
import {canonicalItems,indexCatalog} from '../planner/engine.mjs';
import {ItemIcon} from '../catalog/ItemIcon';
import {Dialog} from '../ui/Dialog';
import {fitsGame,supported,twoHanded,uniqueEquipment} from './loadout.mjs';

const standardLeft=['Head','Chest','Gloves','Boots / Legs','Main weapon'];
const right=['Cape','Accessory','Ring 1','Ring 2','Belt','Off-hand'];
const consumables=['Potion 1','Food 1','Food 2','Food 3','Potion 2'];
const images:BuildImage[]=['warrior','mage','range','exploration','gathering'];
const label=(name:string)=>name==='range'?'Ranged':name[0].toUpperCase()+name.slice(1);
export function BuildCanvas({build,game,canEdit,busy,addVariantTarget,toolbarTarget,onChange}:{build:Build;game:Game;canEdit:boolean;busy:boolean;addVariantTarget:HTMLElement|null;toolbarTarget:HTMLElement|null;onChange:(build:Build)=>void}){
 const [pick,setPick]=useState<string>(),[search,setSearch]=useState(''),[variantDialog,setVariantDialog]=useState(false),[variantName,setVariantName]=useState(''),[renameDialog,setRenameDialog]=useState(false),[copyCurrent,setCopyCurrent]=useState(true),[slotDialog,setSlotDialog]=useState(false),[slotCount,setSlotCount]=useState(1);
 const extraSection=useRef<HTMLElement>(null),variantMenu=useRef<HTMLDetailsElement>(null),imageMenu=useRef<HTMLDetailsElement>(null);
 const catalog=catalogs[game],index=indexCatalog(catalog),variant=build.variants?.find(v=>v.id===build.activeVariantId)||build.variants?.[0],extraCount=variant?.extraSlotCount||0;
 const left=(game==='enshrouded'||game==='duneawakening')?['Head','Chest','Gloves','Legs','Boots','Main weapon']:standardLeft;
 const activeImage=variant?.imageType||build.imageType||'exploration';
 const allItems=uniqueEquipment(canonicalItems(catalog),catalog);
 function change(items:BuildItem[],skills=build.skills,extraSlotCount=extraCount){onChange({...build,items,skills,variants:build.variants?.map(v=>v.id===build.activeVariantId?{...v,items,skills,extraSlotCount}:v)});}
 function switchVariant(id:string){const next=build.variants?.find(v=>v.id===id);if(next)onChange({...build,activeVariantId:id,items:next.items,skills:next.skills,imageType:next.imageType||build.imageType||'exploration'});variantMenu.current?.removeAttribute('open');}
 function makeVariant(){const name=variantName.trim();if(!name||!build.variants||build.variants.length>=20)return;const next:BuildVariant={id:crypto.randomUUID(),name,items:copyCurrent?structuredClone(build.items):[],skills:copyCurrent?build.skills:'',extraSlotCount:copyCurrent?extraCount:0,imageType:activeImage};onChange({...build,variants:[...build.variants,next],activeVariantId:next.id,items:next.items,skills:next.skills,imageType:next.imageType});setVariantDialog(false);setVariantName('');}
 function removeVariant(){if(!build.variants||build.variants.length<2)return;const variants=build.variants.filter(v=>v.id!==build.activeVariantId),next=variants[0];onChange({...build,variants,activeVariantId:next.id,items:next.items,skills:next.skills,imageType:next.imageType||'exploration'});}
 function removeExtra(number:number){const items=build.items.filter(i=>i.slot!==`Extra ${number}`).map(i=>{const n=Number(i.slot.match(/^Extra (\d+)$/)?.[1]);return n>number?{...i,slot:`Extra ${n-1}`}:i;});change(items,build.skills,extraCount-1);}
 const main=index.byId.get(build.items.find(i=>i.slot==='Main weapon')?.itemId||'');
 function slot(name:string){const item=build.items.find(i=>i.slot===name),extra=name.startsWith('Extra '),allowed=extra||supported(game,name),locked=name==='Off-hand'&&twoHanded(main);return <div className={'build-equipment-slot'+(extra?' build-spare-slot':'')+(item?' occupied':'')} key={name} aria-label={`${name} slot`}><div className="build-slot-body"><span className="build-slot-icon">{item?<ItemIcon game={game} id={item.itemId} art/>:<Ban size={20}/>}</span><span className="build-slot-copy"><small>{name}</small><strong>{item?.name||(!allowed?'Unavailable':locked?'Two-handed weapon':'Empty')}</strong></span></div>{extra&&item&&canEdit&&<input className="build-spare-quantity" aria-label={`Quantity in ${name}`} title="Quantity for shopping lists" type="number" min={1} max={999999} value={item.quantity} onChange={e=>{const n=Number(e.target.value);if(Number.isSafeInteger(n)&&n>0&&n<=999999)change(build.items.map(i=>i.slot===name?{...i,quantity:n}:i));}}/>}{canEdit&&allowed&&!locked&&<div className="build-slot-buttons"><button className="icon-button" title={'Choose '+name} aria-label={'Choose item for '+name} disabled={busy} onClick={()=>{setPick(name);setSearch('');}}><Plus size={15}/></button>{item&&<button className="icon-button" title={'Remove '+name} aria-label={'Remove item from '+name} onClick={()=>change(build.items.filter(i=>i.slot!==name))}><Minus size={15}/></button>}</div>}{extra&&canEdit&&<button className="icon-button build-spare-remove" title={'Delete '+name+' slot'} aria-label={'Delete '+name+' slot'} onClick={()=>removeExtra(Number(name.slice(6)))}><Trash2 size={14}/></button>}</div>;}
 return <>{addVariantTarget&&createPortal(canEdit&&<button className="button outline" disabled={busy||!!build.variants&&build.variants.length>=20} onClick={()=>{setVariantName(`Variant ${(build.variants?.length||0)+1}`);setCopyCurrent(true);setVariantDialog(true);}}><Plus size={15}/>Add variant</button>,addVariantTarget)}{toolbarTarget&&createPortal(<>{(build.variants?.length||0)>1&&<div className="build-toolbar-variant"><details className="build-menu" ref={variantMenu}><summary aria-label="Build variant" title="Switch build variant">{variant?.name||'Original'}</summary><div className="build-menu-options">{build.variants?.map(v=><button type="button" className={v.id===variant?.id?'selected':''} key={v.id} onClick={()=>switchVariant(v.id)}>{v.name}</button>)}</div></details>{canEdit&&<><button className="icon-button" title="Rename selected variant" aria-label="Rename selected variant" onClick={()=>{setVariantName(variant?.name||'');setRenameDialog(true);}}><Pencil size={15}/></button><button className="icon-button" title="Delete selected variant" aria-label="Delete selected variant" onClick={removeVariant}><Trash2 size={15}/></button></>}</div>}{canEdit&&<details className="build-menu build-toolbar-image" ref={imageMenu}><summary aria-label="Character image" title="Character image for this variant">{label(activeImage)}</summary><div className="build-menu-options">{images.map(name=><button type="button" key={name} className={name===activeImage?'selected':''} onClick={()=>{onChange({...build,imageType:name,variants:build.variants?.map(v=>v.id===build.activeVariantId?{...v,imageType:name}:v)});imageMenu.current?.removeAttribute('open');}}>{label(name)}</button>)}</div></details>}</>,toolbarTarget)}
 <div className="build-display"><div className="build-equipment-column">{left.map(slot)}</div><div className="build-character" role="img" aria-label={`${label(activeImage)} character artwork`}><img src={`./assets/build-archetypes/${activeImage}.png`} alt=""/><span>{variant?.name||'Original'}</span></div><div className="build-equipment-column">{right.map(slot)}</div></div>
 <div className="build-consumable-strip">{consumables.map(slot)}</div>
 <section className="build-spares" ref={extraSection}><div className="build-spares-heading"><div><h3>Extra items{extraCount>0?` (${extraCount})`:''}</h3><p className="muted small">Carry alternate weapons or any other item from this game.</p></div>{canEdit&&<button className="button outline" onClick={()=>{setSlotCount(1);setSlotDialog(true);}} disabled={extraCount>=24}><Plus size={15}/>Add slots</button>}</div><div className="build-spares-grid">{Array.from({length:extraCount},(_,n)=>slot(`Extra ${n+1}`))}{extraCount===0&&<p className="muted small">No extra items in this variant.</p>}</div></section>
 {variantDialog&&<Dialog title="Add build variant" onClose={()=>setVariantDialog(false)}><div className="build-dialog-fields"><label>Variant name<input aria-label="Variant name" autoFocus maxLength={80} value={variantName} onChange={e=>setVariantName(e.target.value)}/></label><label className="build-checkbox"><input type="checkbox" checked={copyCurrent} onChange={e=>setCopyCurrent(e.target.checked)}/>Copy current loadout into the new variant</label><p className="muted small">Uncheck to start with a blank builder. Existing variants stay in this build.</p><div className="actions"><button className="button primary" disabled={!variantName.trim()} onClick={makeVariant}><Copy size={15}/>Create variant</button><button className="button outline" onClick={()=>setVariantDialog(false)}>Cancel</button></div></div></Dialog>}
 {renameDialog&&variant&&<Dialog title="Rename variant" onClose={()=>setRenameDialog(false)}><div className="build-dialog-fields"><label>Variant name<input aria-label="New variant name" autoFocus maxLength={80} value={variantName} onChange={e=>setVariantName(e.target.value)}/></label><div className="actions"><button className="button primary" disabled={!variantName.trim()} onClick={()=>{onChange({...build,variants:build.variants?.map(v=>v.id===variant.id?{...v,name:variantName.trim()}:v)});setRenameDialog(false);}}>Rename</button><button className="button outline" onClick={()=>setRenameDialog(false)}>Cancel</button></div></div></Dialog>}
 {slotDialog&&<Dialog title="Add extra item slots" onClose={()=>setSlotDialog(false)}><div className="build-dialog-fields"><label>Number of slots<input aria-label="Number of extra slots" type="number" min={1} max={24-extraCount} value={slotCount} onChange={e=>setSlotCount(Number(e.target.value))}/></label><div className="actions"><button className="button primary" disabled={!Number.isSafeInteger(slotCount)||slotCount<1||slotCount>24-extraCount} onClick={()=>{change(build.items,build.skills,extraCount+slotCount);setSlotDialog(false);requestAnimationFrame(()=>extraSection.current?.scrollIntoView({behavior:'smooth',block:'nearest'}));}}>Add slots</button><button className="button outline" onClick={()=>setSlotDialog(false)}>Cancel</button></div></div></Dialog>}
 {pick&&canEdit&&<section className="build-picker" aria-label="Choose build item"><div className="actions"><h3>{pick}</h3><button className="text-button" onClick={()=>setPick(undefined)}>Close picker</button></div><input autoFocus aria-label="Search build items" placeholder="Search this game's items…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="build-picker-results">{allItems.filter(i=>(pick.startsWith('Extra ')||fitsGame(i,pick,game))&&i.name.toLowerCase().includes(search.toLowerCase())).slice(0,50).map(i=><button key={i.id} onClick={()=>{change([...build.items.filter(old=>old.slot!==pick&&!(pick==='Main weapon'&&twoHanded(i)&&old.slot==='Off-hand')),{slot:pick,itemId:i.id,name:i.name,quantity:1}]);setPick(undefined);}}><ItemIcon game={game} id={i.id}/><span>{i.name}<small>{i.category}</small></span></button>)}</div><p className="muted small">{pick.startsWith('Extra ')?'Any item from this game can be carried here.':'Only items matching this equipment slot are shown.'}</p></section>}
 </>;
}
